### ISSUE TITLE
Make source available in transformRequest

### ISSUE THREAD

**Issue by simonseyock** [openlayers/ol-mapbox-style#1008]
It would be convenient to have the source available in the transformRequest call. I would like to set cql filters on some sources dynamically.

In older versions I was able to change the url of the source directly, but this is not possible anymore, as only loaders are used.

**Comment by ahocevar** [comment]
@simonseyock It would be interesting to hear more details about your specific use case. `transformRequest` is useful for things like adding authorization headers or similar. For CQL filters, I feel like creating a new source in the Mapbox style and assigning it to the layer with `updateMapboxLayer()`, or changing the URL directly in the OpenLayers source, which can be obtained with `getSource(map, sourceId)`, would be better. It might also be that what you're actually looking for is an `updateMapboxSource()` function, which should be fairly easy to implement.

**Comment by simonseyock** [comment]
We use pg_featureserv that offers an OGC Feature API with CQL Filtering.

At some points I want to change the cql filter. I then store the filter as a property of the source. The filter is used by a loader that was created after ol-mapbox-style created the intitial sources. The loader is updated by replacing the sources created by ol-mapbox-style. That is of course very hacky and I would love to use another way.

Changing the URL directly in the OpenLayers source will not work anymore because since version 12, ol-mapbox-style does not use the url property anymore.

Creating a new source might work, but the old one will not be needed anymore. I agree that I maybe actually want a `updateMapboxSource()` function :D
