### ISSUE TITLE
Guessing of access token parameter may lead to bad requests

### ISSUE THREAD

**Issue by mbeckem** [openlayers/ol-mapbox-style#1010]
Hi,

we've run into an issue related to the access token handling in `MapboxVectorLayer`.
It seems that `ol-mapbox-style` will always attempt to guess an access token from a mapbox style's URL.
This can lead to broken requests when such a URL points to a public style/service _and_ happens to use other query parameters.

## Reproduction

We have prepared a reproduction demo here: https://github.com/mbeckem/mapbox-layer-access-token-repro

1. Setup the repository and start vite (see README)
2. Open Browser, the invalid requests should be visible in the network console immediately

## Expected behavior

The `MapboxVectorLayer` configured in the demo should use the correct URLs to request individual tiles.
This means that `?f=mvt` must be used when loading a tile (see [style](https://demo.ldproxy.net/strassen/styles/default?f=mbs)).

## Actual behavior

The layer passes **`f=mbs`** instead. This is obviously incorrect and thus rejected by the server.

## Notes

When no access token has been configured on the `MapboxVectorLayer`, it will attempt to guess the parameter from the style's URL, see [completeOptions](https://github.com/openlayers/ol-mapbox-style/blob/6926508ecb4b360e5f8cd960b29c343996a97778/src/apply.js#L120).
In this case, it will infer `f=mbs` to be the access token, overriding the `f=mvt` in the following tile requests.
This behavior cannot be disabled at this time, and the service in question does not allow passing arbitrary query parameters so we can't configure a 'dummy' token either.

## Proposed resolution

We have resolved this in our project by patching an additional supported value for the `accessToken` parameter. We pass `null` explicitly to disable the "guessing" behavior above. I think this would be a backwards compatible change. Ideally the linked behavior in `completeOptions` would go altogether (or not be the default anymore), because style configurations without any access tokens appear to be rather common.

We can open a PR for the `accessToken: null` addition if that direction is acceptable to you.

**Comment by ahocevar** [comment]
Thanks for reporting this problem. Actually the solution is simple - if we do not override existing search params, the original `f=mvt` won't be overwritten with what we think is an access token. See #1013 for the solution.
