### ISSUE TITLE
Maybe a bug in stylefunction

### ISSUE THREAD

**Issue by toddwong** [openlayers/ol-mapbox-style#1067]
https://github.com/openlayers/ol-mapbox-style/blob/bd5fe28b82071ad1da8e5996f5bd491c2aa1156b/src/stylefunction.js#L423C45-L423C45

```javascript
    if (
      (typeof sourceOrLayers == 'string' && layer.source == sourceOrLayers) ||
      sourceOrLayers.indexOf(layerId) !== -1
    ) 
```

If `sourceOrLayers` is a string and `layer.source != sourceOrLayers`, then the `indexOf` function would be `String.prototype.indexOf` instead of `Array.prototype.indexOf`.

**Comment by ahocevar** [comment]
Good find, @toddwong. Thanks! Would you be able to create a pull request with a test and a fix?

**Comment by toddwong** [comment]
@ahocevar Sorry for taking so long to reply. I've been too busy recently. I'll make the PR a little bit later.
