### ISSUE TITLE
Vector tile layer with MVT format clip circle style

### ISSUE THREAD

**Issue by fabienwnklr** [openlayers/ol-mapbox-style#1068]
When i apply mapbox style object, depending on zoom , circle style may be clipped, if i zoom more circle appear completely

illustration:

![image](https://github.com/openlayers/ol-mapbox-style/assets/49644785/31a5691d-2623-4c6d-8f96-364f8ae808c7)

i make a [demo](https://codesandbox.io/p/devbox/olms-clipped-yhv29l?file=%2Fmain.js%3A56%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqfbolcp0006356hselcr07q%2522%252C%2522sizes%2522%253A%255B71.51631455441456%252C28.483685445585436%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwgl5dq01f2356hw7yunqmn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.80781759%252C53.19218241%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqfbolcp0002356h2nwpkjb2%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%252C%2522activeTabId%2522%253A%2522clqw476sn0002356hoei9j64y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqw476sn0002356hoei9j64y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A56%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A56%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqwgkk0f00xy356hwnjvszn6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clqfbolcp0005356hwm1o7w6h%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr0m3jtm00by356g8wotx0gp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr0m3jtm00by356g8wotx0gp%2522%257D%252C%2522clqwgl5dq01f2356hw7yunqmn%2522%253A%257B%2522id%2522%253A%2522clqwgl5dq01f2356hw7yunqmn%2522%252C%2522activeTabId%2522%253A%2522clr0m3h0b00ax356g85okitzp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr0m3h0b00ax356g85okitzp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A21.614583333333343%257D)

**Comment by ahocevar** [comment]
This is a problem with your tiles. In the above screenshot, the point marked by your arrow should be repeated on the neighboring tile on its left, but apparently it isn't.

**Comment by fabienwnklr** [comment]
oh okay sorry, maybe an idea why he doesn't ? because someone else use maplibre and didn't reproduced (example [here ](https://panoramax.ign.fr/#focus=map&map=17.39/43.493527/-1.472284&speed=250))

**Comment by ahocevar** [comment]
You can configure the VectorTile layer with `declutter: true`, then the problem will go away. `clrcle` styles are not subject to deluttering anyway, so all circles will be rendered. https://codesandbox.io/p/devbox/olms-clipped-forked-k6myhj?file=%2Fmain.js%3A96%2C3

**Comment by fabienwnklr** [comment]
Thanks , i solved, but i don't know if it's "normal" when i set `renderMode: "vector"`, circle still clipped 
[https://codesandbox.io/p/devbox/olms-clipped-yhv29l?file=%2Fmain.js%3A56%2C22](https://codesandbox.io/p/devbox/olms-clipped-yhv29l?file=%2Fmain.js%3A56%2C22)

**Comment by ahocevar** [comment]
Yes, that's expected.

**Comment by ahocevar** [comment]
This will be fixed with #15466.
