### ISSUE TITLE
Text-Allow-Overlap and Declutter issues.

### ISSUE THREAD

**Issue by MattMauser** [openlayers/ol-mapbox-style#1103]
I noticed the recent commit to make the text-allow-overlap value be used from the Style sheet:

https://github.com/openlayers/ol-mapbox-style/commit/2f874593f7d7ab6effca6c354794ed094be796af

Is this fully implemented? It seems like the layer's declutter value (including the default if the declutter property is omitted) is taking precedence, regardless what the style json says.

Also, we have some large labels that we want to have the "text-allow-overlap" property because they are important and we want them to always be shown, however; if we set their declutter value to false (like this recent commit seems to be supposed to be doing) then they will no longer show properly along tile boundaries and are cut-off in some instances.

Is there a way to decouple these two functions so that the text still shows properly along vector tile boundaries, but is also not removed by other text. 

This is coming from a large vector tile package that was generated through ESRI software and the style is being applied using the "applyStyle" function. Is there a way to view the style that is generated in the console so I can verify how certain properties are being applied?

There is a codepen here I have been playing with. One of the main text layers I've been looking at is for the capitals (near the stars on the map). If declutter is true, the capital names disappear. If it's false, then they show, however; they now sometimes get cut off.

https://codesandbox.io/p/sandbox/vector-tile-testing-876gvc

Also, probably another issue, but at zoom level 8.3-8.5 and 10.6, layers are not drawing and the page is turning blue / white. Those are at breakpoints, so likely something to do with that.

**Comment by ahocevar** [comment]
Yes, `text-allow-overlap` is fully implemented, but depends on `ol >= 9`. I cannot access your sandbox, so I cannot tell whether you are using v9 of OpenLayers already.

**Comment by MattMauser** [comment]
Ah, sorry. This link should work:

[Sandbox](https://codesandbox.io/p/sandbox/vector-tile-testing-876gvc?file=%2Fpackage.json%3A6%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrqj18ok00073h6gdham47ju%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrqj18ok00033h6gecwovpe3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrqj18ok00043h6gusfxyxel%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrqj18ok00063h6g3bqopdfe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.1084106193669%252C47.8915893806331%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrqj18ok00033h6gecwovpe3%2522%253A%257B%2522id%2522%253A%2522clrqj18ok00033h6gecwovpe3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsknsoe300023h6fftc5c9tm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A23%257D%255D%257D%252C%257B%2522id%2522%253A%2522clsvu4dz500023h6f68klxz70%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A13%257D%255D%257D%252C%257B%2522id%2522%253A%2522clsvyn7ft00023h6fy93vije8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A26%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522clsvu4dz500023h6f68klxz70%2522%257D%252C%2522clrqj18ok00063h6g3bqopdfe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqj18ok00053h6gqwmpd478%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrqj18ok00063h6g3bqopdfe%2522%252C%2522activeTabId%2522%253A%2522clrqj18ok00053h6gqwmpd478%2522%257D%252C%2522clrqj18ok00043h6gusfxyxel%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrqj18ok00043h6gusfxyxel%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.096920796799537%257D)

The ol version is 7.2.2. I tried to change it to 9.0.0, but then I just get a bunch of errors.

**Comment by ahocevar** [comment]
The errors come from parcel, because ol@9 uses ES2020 features that parcel does not support.

**Comment by MattMauser** [comment]
I'm not able to access the sandbox. Probably the same issue I had with not setting the sharing.

**Comment by ahocevar** [comment]
You should have access now. Link above updated.

**Comment by MattMauser** [comment]
Ok, wow. The update from 7.2.2 to 9.0.0 seems to have fixed most of the text issues. Thanks!
