### ISSUE TITLE
Displaying symbols from sprites

### ISSUE THREAD

**Issue by lukastemberga** [openlayers/ol-mapbox-style#1138]
Hi,

I'm trying to add symbols to polygon layer coming from tegola (VectorTiles). I would like to use my custom sprites served from my server. I did manage to make it all load into the app, but just to take a step back I'm first trying to load symbols from matiler demo sprites. 
This is my style.json:
```
{
    "version": 8,
    "sources": {
        "composite": {
            "type": "vector"
        }
    },
    "sprite": "https://demotiles.maplibre.org/styles/osm-bright-gl-style/sprite",
    "layers": [
        {
            "id": "koristenje_prostora",
            "type": "symbol",
            "source": "composite",
            "source-layer": "koristenje_prostora",
            "layout": {
                "icon-image": "airport_11",
                "text-field": "TEST",
                "text-size": 10
            }
        }
    ]
}
``` 

This loads sprites from here as I mentioned:
https://demotiles.maplibre.org/styles/osm-bright-gl-style/sprite.png
https://demotiles.maplibre.org/styles/osm-bright-gl-style/sprite.json

To apply style to layers I'm using this code snippet:
```
const vectorTileSource = new VectorTileSource({
            format: new MVT(layer.layerInfo.featureClass === "Feature" ? { featureClass: Feature } : undefined),
            url: `${layer.layerInfo.url}`,
        });
const vectorTileLayer = new VectorTileLayer({...options}) 

        if (typeof layerStyle === "object" && !(layerStyle instanceof Style)) { // Just an if handling multiple types of style
            applyStyle(vectorTileLayer, "/style.json", {
                updateSource: false,
            });
        }
```

I do manage to get "TEST" text displayed on my polygon layer leading me to believe most of style/layer setup is ok. But I can't figure out why it won't display symbol instead of text. 
I did verify both sprites scheme and image itself get loaded into the app:
![Screenshot from 2024-04-18 13-08-15](https://github.com/openlayers/ol-mapbox-style/assets/42850681/e5fd0fea-29d8-418c-a0c0-6b2cda5213fa)

Am I doing something obviously wrong or do I need to somehow register those images or preload them or something?

Thanks for your help in advance!

**Comment by ahocevar** [comment]
I don't see anything obviously wrong. If you can prepare a jsfiddle or codesandbox or similar, it would be easier to see what is going on.

**Comment by lukastemberga** [comment]
@ahocevar thanks for taking a look!
Sorry it took me a while to prepare a codesandbox, but I did manage to play around with it and got to a conclusion it might be because of displaying a layer that is actually a Polygon layer. I tried adding an Point only layer and sprites are displayed as expected.
You can take a look of the sandbox [here](https://codesandbox.io/p/sandbox/bold-resonance-ypxdlq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv8h7lne00062v6krwvi34e3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv8h7lne00022v6kujl3y2bq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv8h7lne00032v6knfwze5jf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv8h7lne00052v6kpm0b4ptq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv8h7lne00022v6kujl3y2bq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8h7lne00012v6klyz961y0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv8h82gt003p2v6kkof8kg48%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv8h7lne00022v6kujl3y2bq%2522%252C%2522activeTabId%2522%253A%2522clv8h82gt003p2v6kkof8kg48%2522%257D%252C%2522clv8h7lne00052v6kpm0b4ptq%2522%253A%257B%2522id%2522%253A%2522clv8h7lne00052v6kpm0b4ptq%2522%252C%2522activeTabId%2522%253A%2522clv8ikgxc02222v6kxrbgsc6h%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clv8ikgxc02222v6kxrbgsc6h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clv8h7lne00032v6knfwze5jf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv8h7lne00032v6knfwze5jf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I also tried setting style of polygon layer using `fill-pattern` property but I just can't seem to figure it out (and to be honest I don't need fill-pattern, I do need to display a symbol on polygon centroid/point-on-surface)
 
I added both Point and Polygon layers to codesandbox so if you had some idea on how to approach this problem or what I'm doing wrong I would really appreciate it!

**Comment by ahocevar** [comment]
That makes sense, @lukastemberga. ol-mapbox-style does not do anything special to handle polygons with a `symbol` layer, and OpenLayers does not support drawing a symbol for a polygon geometry. Does your example render the symbols in mapbox-gl or maplibre-gl?

Note that the result you'll get for rendering symbols or texts for polygon geometries might not be what you'd expect anyway, because as soon as a polygon occupies more than a single tile, you'll get duplicate symbols and texts.

**Comment by lukastemberga** [comment]
@ahocevar okay, that explains a lot about what is happening. I thought that if you can display text on a polygon layer you could also display symbol/image. 

> Does your example render the symbols in mapbox-gl or maplibre-gl?

If I understood the question correctly - neither, I'm only using OpenLayers to display all the data and symbols.

> Note that the result you'll get for rendering symbols or texts for polygon geometries might not be what you'd expect anyway, because as soon as a polygon occupies more than a single tile, you'll get duplicate symbols and texts.

Yeah I'm aware that behavior occurs because of tiling. I would actually be okay with it since it's only important that I add a symbol to my polygon to describe it's use. If it happens to duplicate the symbol it's not that much of an issue honestly but it would be perfect if it was only on centroid sure.

An idea did occur to me though - would it work if I calculated point on surface in the database and than serve a geometry collection layer through tegola. Basically collection of polygons and points. My question is how would `ol-mapbox-style` handle that?

**Comment by ahocevar** [comment]
> An idea did occur to me though - would it work if I calculated point on surface in the database and than serve a geometry collection layer through tegola. Basically collection of polygons and points. My question is how would ol-mapbox-style handle that?

Not sure about a geometry collection, but if you just add a point on the surface of each polygon to a separate source-layer in the tiles, it will work perfectly fine with `ol-mapbox-style`. That's also how it is done elsewhere.

**Comment by lukastemberga** [comment]
> > An idea did occur to me though - would it work if I calculated point on surface in the database and than serve a geometry collection layer through tegola. Basically collection of polygons and points. My question is how would ol-mapbox-style handle that?
> 
> Not sure about a geometry collection, but if you just add a point on the surface of each polygon to a separate source-layer in the tiles, it will work perfectly fine with `ol-mapbox-style`. That's also how it is done elsewhere.

That does seem like the most obvious solution, sorry it didn't occur to me sooner. I did manage to get it working the way you described by adding another source-layer.
I have tried with geometry collection and it does also work that way!

Thank you for all your help, it is much appreciated!
