### ISSUE TITLE
fill-pattern position bug

### ISSUE THREAD

**Issue by levelost** [openlayers/ol-mapbox-style#1163]
![scr](https://github.com/openlayers/ol-mapbox-style/assets/41239674/48826102-4693-4fec-8787-9d24b19f3e4a)
Seams.

**Comment by ahocevar** [comment]
Does your fill pattern have a size of a power of 2? If it has, you shouldn't be getting the seams.

**Comment by levelost** [comment]
OK. For some reason I decided that it works better than in MapBox )
