### ISSUE TITLE
acc is undefined in stylefunction text-field

### ISSUE THREAD

**Issue by mzmcgrat** [openlayers/ol-mapbox-style#1217]
I'm using this library to create OL-compatible styles from `protomaps-themes-base` (https://github.com/protomaps/basemaps).  I apply the style to a layer with a `PMTilesVectorSource` source using:
```js
stylefunction(layer, {
	version: "8",
	layers: protomaps_themes_base("protomaps", "light"),
	sources: { protomaps: { type: "vector" }}
}, 'protomaps')
```
At certain zoom levels, the style is referencing some text labels, and that triggers the first part of the bug here: https://github.com/openlayers/ol-mapbox-style/blob/main/src/stylefunction.js#L1298

The function passed to `textField.sections.reduce`  should `return acc` on that line instead of just `return`.  The next iteration of the function receives the previous accumulator value of `acc`, which is now `undefined`, so things like `acc.push()` will throw an error.

There's more to my issue than that, but I'm still trying to determine whether it's related to the style itself.

**Comment by ahocevar** [comment]
Good find! Would you be able to create a pull request with the suggested fix?

**Comment by mzmcgrat** [comment]
Done.  This is my first pull request, so hopefully I did it right.  Any feedback would be welcome.
