### ISSUE TITLE
expandUrl is not a function error

### ISSUE THREAD

**Issue by gottesman** [openlayers/ol-mapbox-style#1227]
I'm trying to use the applyStyle function to a VectorTile layer and it returns an error:
util.js:242 Uncaught (in promise) TypeError: f.expandUrl is not a function
I'm using javascript version of OpenLayers  from [jsdelivr.net cdn](https://cdn.jsdelivr.net/npm/ol/dist/ol.js)

![image](https://github.com/user-attachments/assets/38b1a3bd-4543-45aa-93dc-eab78bae4249)

This is the way i've implemented it:

![image](https://github.com/user-attachments/assets/1b87d289-c8ff-40fd-aabf-c356d8d2cc0f)
![image](https://github.com/user-attachments/assets/b884b463-8599-4faf-8b56-549fdc5a0466)

**Comment by ahocevar** [comment]
Thanks for reporting this. We need to get rid of `expandUrl()`, because it is not part of the OpenLayers API and has moved to a different path in the full build. #1228 will fix it.
