### ISSUE TITLE
operator match and static olms.js

### ISSUE THREAD

**Issue by stefanoferrijrc** [openlayers/ol-mapbox-style#126]
I'm  trying to make a feature classification using the olms.js (https://unpkg.com/ol-mapbox-style@2.1.1/dist/olms.js) and the operator match like:

{ 
	"version": 8, 
	"sources": { "type": "vector" }, 
	"layers": [ {
		"source": "MyData", 
		"paint": {
			"circle-radius": 4, 
			"circle-color": [ 
				"match", ["string", ["get", "classes"]] , 
				"class1","rgba(30, 171, 30, 1)", 
				"class2","rgba(210, 124, 12, 1)", 
				"class3","rgba(250, 0, 0, 1)", 
				"class4","rgba(113, 30, 12, 1)", 
				"rgba(255,255,255,1)" 
			] 
		}
	}]
}

But I get only black ("default") points.
Is it because match requires Mapbox GL JS >=  0.41.0 ?

Thanks !

**Comment by ahocevar** [comment]
Expressions are not supported in v2.x of ol-mapbox-style. Please use the latest version (currently v3.6.4).

**Comment by fredj** [comment]
Can we close this issue?
