### ISSUE TITLE
why icon is black rendered in openlayers

### ISSUE THREAD

**Issue by wangzy123** [openlayers/ol-mapbox-style#132]
Hı ,
I am using olms to create an OpenLayers map from a glStyle. I find the icon is black,but it is not black on the sprite.png.How can I do to resolve this problem?
Code:
 var map = new Map({
    target: 'map',
    view: new View({

        center: [0, 0],
        zoom: 2
    })
 });
olms(map, 'http://vectortile.geo-compass.com/api/v1/styles/xjl/rkmZEqQSN/publish?access_key=7c611870843304ad94ce4df5afed4d5f');
Results:
![image](https://user-images.githubusercontent.com/29917668/52843560-70fe7080-313d-11e9-9053-2bb5be3830e1.png)
sprite:
![image](https://user-images.githubusercontent.com/29917668/52843680-c76baf00-313d-11e9-9ee4-59a890cea20e.png)

**Comment by ahocevar** [comment]
Your style sets the icon color to black:
```json
        "icon-color": "#000000",
```
If you remove that line, the icon should appear as in the sprite sheet.

**Comment by wangzy123** [comment]
@ahocevar ,
Thank you!The problem was solved according to your suggestion.
