### ISSUE TITLE
Support text-translate

### ISSUE THREAD

**Issue by HarelM** [openlayers/ol-mapbox-style#134]
I would like to use a text and an icon for a point.
The following mapbox code is what I would like to use:
```json
{
      "id": "park_label",
      "type": "symbol",
      "source": "IHM",
      "source-layer": "park",
      "filter": ["all"],
      "layout": {
        "icon-image": "RTG",
        "text-size": {"stops": [[8, 5], [16, 15]]},
        "icon-size": {"stops": [[9, 0.15], [12, 1]]},
        "text-font": ["Open Sans Regular"],
        "icon-offset": [0, -2],
        "visibility": "visible",
        "text-field": "{name:he}",
        "icon-anchor": "center",
        "text-padding": 0
      },
      "paint": {
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255,255,255,0.75)",
        "text-halo-blur": 1,
        "text-translate": [0, 15],
        "text-translate-anchor": "viewport"
      }
```
However, the text is rendered on top of the icon and not below/above the icon.
I'm guessing `offsetX` and `offsetY` can be used to support this, right?
I'm a bit new to this code, so it might take me a while to get into it, but I'd love to help out testing it.

**Comment by ahocevar** [comment]
We'd gladly accept a pull request to add support for `text-translate`. But for your use case, I think [`text-offset`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-offset) would be sufficient.
