### ISSUE TITLE
Multiple source : Label decluterring

### ISSUE THREAD

**Issue by pakb** [openlayers/ol-mapbox-style#136]
When multiple sources are described in the mapbox style, OLMS adds them as separate LayerGroup in OL, thus making decluttering not possible with labels overlapping each others in the different sources.

You can see this in action while looking at Basel in this codepen, there's a label from OSM that is underneath our label while it is not there with Mapbox.
https://codepen.io/pakb/full/OddJwX

**Comment by ahocevar** [comment]
OpenLayers currently has no option to do decluttering on the map level. It is always done on the layer level. In this regard, it is different from mapbox-gl.

It would be possible to give OpenLayers an option to declutter on the map level. But looking at the use case (labels from two different sources, where one appears to only contain labels), I'd suggest that combining the two sources upon tile creation would make more sense, especially given the increased resource demands of additional vector tile layers. As a rule of thumb, mobile (i.e. battery life) friendly vector tile maps have as few OpenLayers layers as possible.

**Comment by pakb** [comment]
Maybe a good way of solving this would be to provide in olms an OpenLayer custom loader for mapbox styles, as you had hinted me on this PR https://github.com/geoadmin/mf-geoadmin3/pull/4523 ?
Single LayerGroup for every source, this way decluterring can happen

**Comment by ahocevar** [comment]
Yes, this is a good suggestion and reduces resource consumption. Map authors only need to take care that they do not add a raster layer between layers of labels. Because in this case, ol-mapbox-style would have to create 3 layers: 1 vector tile layer below the raster layer, 1 raster layer, 1 vector tile layer above the raster layer. But I guess since labels below a raster label are not very desirable, we can neglect this corner case.

**Comment by ahocevar** [comment]
Custom loaders are currently facing a problem that's blocking us here. See openlayers/openlayers#9293.

**Comment by ahocevar** [comment]
I'm currently working on this.

@pakb, please note that this change will only fix your issue when all sources have the same range of zoom levels. This is currently not the case with the sources in your fiddle. One has `maxzoom: 14`, and the other has `maxzoom: 15`.

**Comment by pakb** [comment]
Ok we'll fix that quickly. Any other properties we should be cautious with for this use case?

**Comment by ahocevar** [comment]
@pakb The properties that need to match are `minzoom`, `maxzoom` and `tileSize`.

**Comment by pakb** [comment]
I've tried a version of our style with same `maxzoom`, but it doesn't work well with OSM data at high zoom level (most things disappear past a certain point). It is not a simple quick fix to the style we have to look into the data.

**Comment by pakb** [comment]
We don't have data for OSM beyond zoom level 14, so I can't set this `maxzoom` at the same number for both sources without breaking stuff, or hiding part of our data (which our data holder will never accept).
Why is it mandatory to have the same max zoom? Isn't that breaking the concept of vector tiling where you can have multiple source, with each its `maxzoom` set to its optimum to lower data transfer?

**Comment by pakb** [comment]
@ahocevar Is there a branch or PR where I can test you solution?

**Comment by ahocevar** [comment]
Unfortunately I can not provide anything to test. I ran out of the budget I got from the association.

**Comment by danduk82** [comment]
@ebelo are you aware of this?

@ahocevar if you have no budget from OL association, you could have addressed this problem earlier. Now we have been 2 weeks with complete silence from your side and this is your answer?

**Comment by ahocevar** [comment]
@danduk82 Emmanuel is aware of this. On April 1st, he told me to stop working on this and to provide a roadmap for the next steps. I have provided him a complete assessment with roadmap and estimates on April 1st, and have never gotten a response.

**Comment by ahocevar** [comment]
Actually I just found a confirmation of budget for April from Emmanuel in my spam folder. Sorry for the delay @danduk82, I'll give the completion of this work the highest possible priority.

**Comment by ahocevar** [comment]
Because of the [concerns raised by @pakb](https://github.com/openlayers/ol-mapbox-style/issues/136#issuecomment-483150227), I think we'll be persuing a different approach, i.e. a shared declutter tree across all layers. The result for the above example map would then look like this: https://github.com/openlayers/ol-mapbox-style/issues/136#issuecomment-483150227.

Would this be an acceptable solution? If so, we can make the required changes in OpenLayers.

**Comment by pakb** [comment]
Yep, that would be what we're looking for!
Little improvement I see on this codesandbox : if you could take into account the ordering in the Mapbox style to let the highest labels be chosen when in conflict with another, that would be great.
(Look at Rheinfelden, near Basel for an example, it's on both side of the border, but we would like the Swiss label to be chosen over the German one when zoomed out)

**Comment by ahocevar** [comment]
I have implemented the correct render order with two pull requests (both still work in progress: #203 and openlayers/ol#9466). The result can be seen here: http://ahocevar.net/ol-mapbox-style/dist/tilejson-vectortile.html.

**Comment by pakb** [comment]
working like a charm, thanks a lot!
