### ISSUE TITLE
Add support for font styling described in mapbox style

### ISSUE THREAD

**Issue by pakb** [openlayers/ol-mapbox-style#137]
Not all properties of mapbox styling regarding fonts are supported by OLMS.
Thus far I've seen that :

- `text-letter-spacing`
- `text-padding` ✅ 

Are not supported. Those two are major no-go's for us, as they help us greatly in ligthening the map.
On this codepen you can see lake labels without letter spacing, and too much peak labels because text-padding is not supported : https://codepen.io/pakb/full/daaeyb

**Comment by pakb** [comment]
For `letter-spacing`, I'm looking at how font are set for the text, but it doesn't seem to be possible to alter this CSS property in OLMS.
In OpenLayers I don't really understand how ol/style/Text are given to the canvas to be drawn, and how to add support for this in this style. Any hint @ahocevar ?

**Comment by ahocevar** [comment]
The most pragmatic approach would be something along the lines of https://stackoverflow.com/questions/8952909/letter-spacing-in-canvas-element#answer-14991381. We already pre-process text (split into lines): https://github.com/openlayers/ol-mapbox-style/blob/4cea6523e56774c48c5e393d3e9a72c2b8911e07/stylefunction.js#L604

Just above that line, `wrappedLabel` could be changed to add unicode space characters of the appropriate length to match the given `text-letter-spacing´.
