### ISSUE TITLE
Rendering of small features, min-width?

### ISSUE THREAD

**Issue by pakb** [openlayers/ol-mapbox-style#139]
In mapbox, small feature like rivers seem to have a min-width for rendering as they show up on the map, where they are hidden (because too small for rendering?) in OL after loading mapbox style via olms.

Example in this codepen : https://codepen.io/pakb/full/gqqzyo

**Comment by ahocevar** [comment]
The rivers in your codepen are polygons (not lines) from the `hydrology_river` layer of your style. The difference between ol-mapbox-style and mapbox-gl comes from the fact that we only create a polygon stroke when a `fill-outline-color` is set in the style. This is a small deviation from the spec that gives us faster polygon rendering in many cases: https://github.com/openlayers/ol-mapbox-style/blob/4cea652/stylefunction.js#L370-L389

We could easily change the logic to add the stroke for all polygons, but we'd need to do thorough testing to ensure that there is no performance penalty that doesn't justify the visual benefit.
