### ISSUE TITLE
add text-rotation-alignment

### ISSUE THREAD

**Issue by GD-Aichi** [openlayers/ol-mapbox-style#140]
```javascript
const textRotationAlignment = getValue(layer, 'layout', 'text-rotation-alignment', zoom, f);
if (textRotationAlignment == 'map') {
  text.rotateWithView_ = true;
}
```

**Comment by ahocevar** [comment]
Thanks for reporting this @GD-Aichi. Would you be able to bake this into a pull request? Instead of setting the private `rotateWithView_` property, another pull request against OpenLayers would be nice to add a `setRotateWithView()` setter.

**Comment by fredj** [comment]
@GD-Aichi, @ahocevar I've added the `setRotateWithView` function in OpenLayers, see https://github.com/openlayers/openlayers/pull/9240
