### ISSUE TITLE
Circle with opacity=0 rendered as black Circle

### ISSUE THREAD

**Issue by tristanbenier** [openlayers/ol-mapbox-style#148]
Hi,

I am facing an, issue with your lib:

I created a style looking like this:
```
const DEFAULT_STYLE = {
  version: 8,
  name: 'default-style',
  sources: {
    'default-style': {
      type: 'geojson',
    },
  },
  layers: [
    {
      id: 'default-layer-point-style',
      type: 'circle',
      source: 'default-style',
      paint: {
        'circle-radius': 10,
        'circle-color':'#ff0000',
        'circle-stroke-color': '#ff0000',
        'circle-stroke-width': 0.5,
        'circle-opacity': 1,
        'circle-stroke-opacity': 1,
      },
    },
    {
      id: 'default-layer-line-style',
      type: 'line',
      source: 'default-style',
      paint: {
        'line-color': '#ff0000',
        'line-width': 2,
        'line-opacity': 1,
      },
    },
    {
      id: 'default-layer-polygon-style',
      type: 'fill',
      source: 'default-style',
      paint: {
        'fill-color': '#ff0000',
        'fill-outline-color': '#ff0000',
        'fill-opacity': 1,
      },
    },
  ],
};
```

I create my stylefunction using your `stylefunction` method, and apply it to my features layer.
Everything is rendered as I want.

![image](https://user-images.githubusercontent.com/285037/53344557-3ce03800-3913-11e9-9ef9-79f51c6eb842.png)

![image](https://user-images.githubusercontent.com/285037/53344614-6305d800-3913-11e9-8767-4b4757499463.png)

However, when I set the different `opacity` values to `0`, the lines and polygons are hidden, but the points are rendered as black points.

![image](https://user-images.githubusercontent.com/285037/53344554-36ea5700-3913-11e9-9308-3107b92aa15f.png)

It looks like it is related to the `iconImg` generated on line https://github.com/openlayers/ol-mapbox-style/blob/master/stylefunction.js#L560

When I set the opacity to the `iconImg` like this: `iconImg.setOpacity(circleOpacity);` before setting the image to the style, everything works as wanted.

I don't know if it's the right thing to do, but I guess there is definitely something to do with this section of the code.

Thanks !

**Comment by tristanbenier** [comment]
Note that if I comment the lines 114, 115 and 116, I also get the correct result. https://github.com/openlayers/ol-mapbox-style/blob/master/stylefunction.js#L114
```
// if (color[3] === 0) {
//   color = undefined;
/  }
```

**Comment by ahocevar** [comment]
Thanks for reporting this. #148 should fix your issue. Can you please verify?

**Comment by tristanbenier** [comment]
Hi,

Thanks @ahocevar for your reactivity!
How can I install the package from your branch ?

I tried `npm install --save openlayers/ol-mapbox-style#opacity` but it doesn't work...

**Comment by tristanbenier** [comment]
@ahocevar Thanks for your reactivity, it's impressive !

I've tried with your changes, it works well ! :)
