### ISSUE TITLE
getFonts is not caching the results

### ISSUE THREAD

**Issue by fredj** [openlayers/ol-mapbox-style#153]
The function is checking if the font is in the `fontFamilies` cache object but never stores anything in that cache: https://github.com/openlayers/ol-mapbox-style/blob/fc28c683f4e687ab188636a405b52a8bc8b3c09f/index.js#L58-L60

Is this cache supposed to store the font name by families? Something like:
```js
{
  "Noto Sans": ["Noto Sans Bold", "Noto Sans Regular"]
}
```

**Comment by ahocevar** [comment]
Actually looking again, what I said above makes no sense.

**Comment by ahocevar** [comment]
@fredj I have created #154, which should fix this. Do you think you'd be able to add tests to that pull request? Would be much appreciated. Thanks!
