### ISSUE TITLE
Infinite loop requesting tiles

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol-mapbox-style#164]
With v4, the map defined by https://maps.tilehosting.com/styles/topo/style.json produces an infinite loop of tile requests. This was not the case with v3.x.

**Comment by ahocevar** [comment]
This might be an issue with the library, or an issue with OpenLayers v6, or both. Investigating now.

**Comment by fredj** [comment]
We have the same issue with the mapbox-style example in OpenLayers master:
https://openlayers.org/en/master/examples/mapbox-style.html

**Comment by ahocevar** [comment]
Making slow progress on this. Part of the issue is that https://maps.tilehosting.com/data/contours.json, a TileJSON source used by the style in question, has a `"minzoom": 9`. This should result in a layer minzoom of 9 too, but it doesn't. I'm creating a pull request for this problem first.
