### ISSUE TITLE
Use tileSize from the source configuration

### ISSUE THREAD

**Issue by fredj** [openlayers/ol-mapbox-style#165]
If present, use the `tileSize` property from in the `raster` source.

See https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-raster-tileSize

Examples:
```json
"hillshading": {
  "type": "raster",
  "url": "https://maps.tilehosting.com/data/hillshades.json?key=RT4ksaerAd67XEsgQmSo",
  "tileSize": 256
}
```

**Comment by ahocevar** [comment]
That should be the case already, because we create a TileJSON source with that data as inline TileJSON.
