### ISSUE TITLE
Use mapbox-gl npm package instead of mapbox-gl-style-spec

### ISSUE THREAD

**Issue by fredj** [openlayers/ol-mapbox-style#171]
mapbox-gl-style-spec doesn't exist anymore:
https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/README.md

**Comment by ahocevar** [comment]
The repository does not exist. The package `@mapbox/mapbox-gl-style-spec` is published from the https://github.com/mapbox/mapbox-gl-js repository. See https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/package.json.
