### ISSUE TITLE
sytleFunction参数问题

### ISSUE THREAD

**Issue by zl142900** [openlayers/ol-mapbox-style#184]
Why is it that the spriteImageUrl property that I wrote doesn't render there

![1553064691(1)](https://user-images.githubusercontent.com/42824619/54664588-a1ac3e00-4b1f-11e9-9bb9-8687b941cbd3.jpg)

**Comment by ahocevar** [comment]
Two things are wrong in your code:

1. Your arguments are in the wrong order. See https://www.npmjs.com/package/ol-mapbox-style#parameters-7. `spriteData` goes before `spriteImageUrl`. 
2. `spriteData` has to be provided as json object, not as url.

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/54728800-ecc75f00-4bba-11e9-95a2-75f5bf9506e4.png)
I adjusted the position of these two parameters, but still did not achieve.I debug the code found Source this parameter is undefined, you have a complete parameter example, let me see.Thank you very much

**Comment by ahocevar** [comment]
You solved (1), but not (2). Instead of passing `spriteData` as url, you need to load it and pass the data.
```
const urls = [
  'data/empty_style.json',
  spriteData
];
Promise.all(urls.map(u=>fetch(u))).then(responses =>
  Promise.all(responses.map(res => res.json()))
).then(jsons => {
  const [glStyle, spriteDataJson] = jsons;
  stylefunction(layer, glStyle, 'guiyang', undefined, spriteDataJson, spriteImageUrl);
  // ...
})

**Comment by zl142900** [comment]
Thank you very much. It has been settled.I would like to ask which version of openlayser is used for this project

**Comment by ahocevar** [comment]
https://github.com/openlayers/ol-mapbox-style/blob/14b877515fa356e7944193ad7e1535a2998b7116/package.json#L34-L36

**Comment by zl142900** [comment]
Do you have the tool for transforming mapbox style sheet into openlayers

**Comment by ahocevar** [comment]
> Do you have the tool for transforming mapbox style sheet into openlayers
That's the purpose of this library. See https://github.com/openlayers/ol-mapbox-style#olms and how it's used e.g. in https://unpkg.com/ol-mapbox-style@4.2.1/dist/tilejson-vectortile.html.

**Comment by zl142900** [comment]
What I mean is that the mapbox style sheet (json file) can be converted into the openlayers style sheet (json file). What I need is that the two files can be converted, and now your project USES openlayers to load the mapbox style sheet

**Comment by ahocevar** [comment]
This is exactly what ol-mapbox-style does. OpenLayers uses functions (no json) for styling. ol-mapbox-style reads a Mapbox Style json and  creates OpenLayers style functions from it.

**Comment by zl142900** [comment]
Ok, thank you very much for your reply, which is very helpful to me

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/55927061-4238de00-5c46-11e9-9db9-5c436c277fe4.png)
I wrote it your way, but he loaded the map like this
![image](https://user-images.githubusercontent.com/42824619/55927111-6d233200-5c46-11e9-8d11-ac4b370605ad.png)
Is it because the font parameter is wrong
