### ISSUE TITLE
labels following polylines bend a lot

### ISSUE THREAD

**Issue by pakb** [openlayers/ol-mapbox-style#186]
https://codepen.io/pakb/full/JzeXwY

I don't how the renderer decides where to place labels, but maybe there should be some kind of max angle safeguard so that it doesn't bend label that much?

**Comment by fredj** [comment]
@pakb `text-max-angle` was added in #181, did you tried with this version (master)?

**Comment by pakb** [comment]
I'm using v4.2.1 on a CDN which doesn't incorporate this change yet. So I'll wait for next release and quickly give a feedback if this solves the issue.

**Comment by pakb** [comment]
I've updated the codepen with latest master of both OL and OLMS.
It's a bit better, but there are still big bents.
Maybe we could improve how the location of the label is chosen. Mapbox seems to choose the straightest part of the shape to place the labels.
