### ISSUE TITLE
Performance issue with circle rendering

### ISSUE THREAD

**Issue by mshubin** [openlayers/ol-mapbox-style#193]
Hi,

I have a VectorTileLayer which uses `stylefunction` applied to render a huge volume of points.
But, when we try to render using 'circle' type we have the performance issues causing an 'Aw Snap!' crash in browser.

After a quick investigation I've found that `iconImageCache` is checked when creating a 'circle'-related styles but unfortunately never updated (https://github.com/openlayers/ol-mapbox-style/blob/master/stylefunction.js#L498)

By updating the iconImageCache the problem disappears:
`iconImg = iconImageCache[cache_key] = new Circle({`

Thank you in advance,

**Comment by fredj** [comment]
Thanks @mshubin ! 
Would you be able to provide a pull request?

**Comment by mshubin** [comment]
Done ;)

Thank you very much for your work !
