### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by AidasK** [openlayers/ol-mapbox-style#196]
I tried using `applyBackground`, but background is still transparent in exported image. Any way to set it to white? 
```js
    olms.apply(map, styleJson);
    olms.applyBackground(map, {
        "version": 8,
        "name": "background",
        "metadata": {
            "mapbox:autocomposite": true,
            "mapbox:type": "template"
        },
        "sources": {},
        "layers": [
            {
                "id": "background",
                "type": "background",
                "paint": {
                    "background-color": "#f00",
                    "background-opacity": 1
                }
            }
        ]
    });

        map.renderSync();
        map.once('rendercomplete', function(event) {
            var canvas = event.context.canvas;
            canvas.toBlob(function(blob) {
                saveAs(blob, 'map.png');
            });
        });
```

![map (24)](https://user-images.githubusercontent.com/2088484/55683544-bb37ed00-5949-11e9-944d-97f0f57b0663.png)

**Comment by AidasK** [comment]
`applyBackground` method only updates background color of the `div` container which holds the canvas. That's why `canvas.toBlob` method exports transparent BG. How do I set a background color on the canvas?

**Comment by fredj** [comment]
In OpenLayers version 6, `canvas.toBlob` will not be available anymore.
You can use a library like [dom-to-image-more](https://www.npmjs.com/package/dom-to-image-more) to export the map's div as an image. See this OpenLayers example: https://openlayers.org/en/master/examples/export-map.html

**Comment by AidasK** [comment]
Hope OpenLayers v6 will be released this week :) 
Though "dom-to-image-more" does not support safari and IE browsers, but it should not be a dealbreaker for me.

**Comment by fredj** [comment]
Note: instead of dom-to-image-more, we're now using [html-to-image](https://www.npmjs.com/package/html-to-image) in the OpenLayers example
