### ISSUE TITLE
olms applied multiple times

### ISSUE THREAD

**Issue by AidasK** [openlayers/ol-mapbox-style#215]
How can I change olms style with a button? My current approach is:
```js
import {default as olms} from 'ol-mapbox-style';
...
olms(map, styleJson1)
button.click(function () {
    olms(map, styleJson2)
});
```
It works, but it leaves some styles from `styleJson1`. It would be great to destroy current layer and apply a new style afterwards.

**Comment by ahocevar** [comment]
Better handling of updates is a planned feature.

For now, you can change your code to do something like
```js
button.click(function() {
  map.getLayers().clear();
  olms(map, styleJson2);
});
```

**Comment by AidasK** [comment]
Solution provided above does not work anymore and I can see some parts of graphics from previous styles after clearing and applying a different style.

**Comment by ahocevar** [comment]
Can you provide a working example that shows the problem? I cannot think of anything that has changed that would make the above solution fail.

**Comment by AidasK** [comment]
Thanks @ahocevar for taking a look. I have reproduced this issue on codepen. The Idea behind it is that if you click button "Pink" both maps should show the same as they will be using the same style. Unfortunately first map still has some bugged state from the last style and it can not update. 
https://codepen.io/AidasK/pen/NWzLEBL

Before changing the style:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2088484/204897700-55eec62e-123a-4a62-aec1-b4ae354c08a0.png">
After changing first map style to pink:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/2088484/204897812-f11e9d66-4b84-49a3-8676-c271d905b7f3.png">

**Comment by ahocevar** [comment]
I tried to make your example work with v9.2.4, but it seems the pink style has something the new version does not like. However, I did observe something: sometimes, the first loaded map looks the same as the second, resulting in this:
<img width="1009" alt="Untitled" src="https://user-images.githubusercontent.com/211514/204935026-67d130d2-1e6b-421c-983c-7160452c1515.png">
So maybe there is really something wrong with the pink map?

**Comment by ahocevar** [comment]
The problem with recent versions is that once a background is configured, it won't go away easily, because postrender functions on the map are used.

I created #746, which introduces a smarter background handling, and will resolve this issue.

**Comment by AidasK** [comment]
Legend! Thanks a lot @ahocevar
