### ISSUE TITLE
Placing images along line with "symbol-placement": "line"

### ISSUE THREAD

**Issue by kbbaker** [openlayers/ol-mapbox-style#230]
Is the layout property "symbol-placement" to place icon images along a line supported? With "symbol-placement" set to line, I only get a symbol placed at the midpoint of the line.

example of my basic "symbol" layer type:

`{
		"id": "dir",
		"type": "symbol",
		"source": "test",
		"source-layer": "this-layer-to-test",
        "minzoom": 12,
		"layout": {
            "icon-image": "arrow",
            "icon-rotation-alignment": "map",
            "symbol-avoid-edges": false,
            "symbol-spacing": 10,
            "icon-allow-overlap": false,
            "icon-size": 0.7,
            "icon-padding": 2,
            "icon-rotate": 90,
            "symbol-placement": "line"
        },
        "interactive": true
	}`

Regards,

Kevin

**Comment by ahocevar** [comment]
The interesting part in your style is the `symbol-spacing` property, which is not (yet) supported by ol-mapbox-style. According to the spec, your style would render the symbol along the line every 10 pixels, but due to the missing `symbol-spacing` support, ol-mapbox-style only renders it once at an anchor near the midoint of the line.

**Comment by kbbaker** [comment]
Thank you for the insight. 

just out of interest: Are there any intention to integrate this layout property in the (near) future?

**Comment by ahocevar** [comment]
@kbbaker I'd like to add it, but it would be a quite involved change. If development could be funded in some way, it is likely that it can happen in the near future. Would you be interested in providing some funding? As an alternative, we'd also accept pull requests with the necessary changes, and I could provide some guidance.

**Comment by kbbaker** [comment]
Funding is certainly an option if this helps develop of the current implementation of the style specifications. How would this funding approach work and do you have an estimation of cost? Helping the development through a pull request could also be an option. Do you have pointers on where the adjustments should be made? I presume in the stylefunction.js?

**Comment by ahocevar** [comment]
This would be quite an involved change, with changes to `stylefunction.js` in this library, and the way we determine suitable subsets of a linestring for rendering in the OpenLayers core library. Including tests and performance optimizations, this can easily take up a week of full-time work.

**Comment by jeff3780** [comment]
@ahocevar , did support for `symbol-spacing` property ever get added to ol-mapbox-style? I am trying to increase the density of road labels as one zooms in. This is for a vector tiles source rendered with OpenLayers using a Mapbox style specification through ol-mapbox-style.  I found this thread while troubleshooting why changes in that particular setting are not reflected on the map even though changes to other settings in the same layout section can be seen. Therefore I wanted to confirm if `symbol-setting` support is still in a backlog.  Thanks very much

**Comment by ahocevar** [comment]
No, this has not been added (yet).

**Comment by aprinslo1** [comment]
> 

Do we understand the effort to make the text symbol-placement frequency change. Who do we contact to get an estimate?

**Comment by ahocevar** [comment]
`symbol-spacing` was implemented with #768.
