### ISSUE TITLE
error when tile load

### ISSUE THREAD

**Issue by lzp0070007** [openlayers/ol-mapbox-style#234]
![image](https://user-images.githubusercontent.com/5045130/66459100-e6d99280-eaa6-11e9-94ac-698dca82138d.png)
Uncaught Error: Tile load sequence violation

when I move the map,some error like this  happen, and after the error,the  map  donot load tile again,Any help from you will be greatly appreciated

**Comment by ahocevar** [comment]
@lzp0070007 Can you please share a minimal example that exposes the issue, e.g. on https://codesandbox.io/? Please create the example with `ol@6.0.1` and `ol-mapbox-style@5.0.0-beta.3`. This will help us reproduce and eventually fix the issue.
