### ISSUE TITLE
text-padding属性设置的值不起作用

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/ol-mapbox-style#239]
在样式单中设置text-padding的值，在stylefunction中可以读取到这个值，但是不起作用，不知道是不是我用中文的问题
![image](https://user-images.githubusercontent.com/31643589/66989881-c4bfc000-f0f7-11e9-80c7-359b8ddbd61a.png)
![image](https://user-images.githubusercontent.com/31643589/66990114-2da73800-f0f8-11e9-9076-7a4a832bce52.png)

**Comment by ahocevar** [comment]
Please note that the project language is English. We'd appreciate if you could report your issues in that language.

**Comment by yiwenzhang666999** [comment]
Set the text-padding value in the style sheet. You can read this value in the stylefunction, but it doesn't work. I don't know if I use Chinese.
