### ISSUE TITLE
Add customProperties parameter to styleFunction

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/ol-mapbox-style#240]
relates to #180
This parameter would allow you to style interactions in the glStyle

**Changes to styleFunction**

```
const styleFunction = function(feature, resolution, customProperties) {
    const properties = !customProperties ?
         feature.getProperties() : 
         Object.assign(feature.getProperties(), customProperties);
```
**Example Usage**
```
layer.setStyle(function (feature, resolution) {
      const selectedFeature = selectedFeatures.includes(feature.get(featureIdentifier));
      if (selectedFeature ) {
        return styleFunction(feature, resolution, { selected: 'true' });
      } else {
        return styleFunction(feature, resolution);
      }
    });
  }
```
Thoughts?

**Comment by ahocevar** [comment]
Did you mean to create this ticket in https://github.com/openlayers/openlayers?

What you're trying to achieve can be solved in different ways already. All of the ways below are faster than your suggestion, and the last one (mutate feature properties) allows you to define all your styles in a Mapbox Style object, without creating any OpenLayers style objects or style functions.

### Feature styles
```js
function selectFeature(feature) {
  feature.setStyle(selectedStyle);
}
function unselectFeature(feature) {
  feature.setStyle(undefined);
}
```

### Wrapper style function
```js
layer setStyle(function(feature, resolution) {
  if (feature.getUid() in selectedFeatures) {
    return selectionStyleFunction(feature, resolution);
  } else {
    return styleFunction(feature, resolution);
  }
});
```
### Mutate feature properties
```js
function selectFeature(feature) {
  feature.set('selected', true);
}
function unselectFeature(feature) {
  feature.set('selected', undefined);
}
```

**Comment by Benjaki2** [comment]
Thanks for the examples @ahocevar. I might go the wrapper style function route.

The reason I thought this Parameter would be helpful was because I was having trouble accessing the actual features. For example: `the layer.setStyle` & `forEachFeatureAtPixel` callbacks gives me `renderFeatures`, which seem to be without setters. Can you think of a way to get around that? Thanks again!

**Comment by ahocevar** [comment]
You can configure your `ol/format/MVT` instance with `featureClass: Feature` (where `Feature` is the `ol/Feature` constructor). But that comes with a performance penalty.

**Comment by Benjaki2** [comment]
Thanks for the help!
