### ISSUE TITLE
Internet Explorer 11 

### ISSUE THREAD

**Issue by pelord** [openlayers/ol-mapbox-style#246]
Yeah I know. Internet Explorer 11. (shame) 

I use ol-mapbox-style inside my project ([GitHub igo2-lib](https://github.com/infra-geo-ouverte/igo2-lib)). 

Everything is normal on Firefox, Edge, Chrome, no surprise.

Here the errors I get on Internet Explorer 11
- Const must be initialized => solved manually by replacing into the package : for(const by for(let
- Hereafther:
       - An error about the foreach definition
       ![image](https://user-images.githubusercontent.com/7397743/69644326-8096d800-1032-11ea-8008-065e1b6c7b53.png)
       - An error about the .map definition ....
       - I've stoped there... but seem to still have some issues.

Initially, I've checked if it was my project causing the error but the OpenLayers demo also have the issue. 

My project demo : https://infra-geo-ouverte.github.io/igo2/
Openlayers demo: https://openlayers.org/en/latest/examples/mapbox-style.html

**Comment by pelord** [comment]
Seem to be related to #199

**Comment by ahocevar** [comment]
This is indeed the same issue as #199. In your case, it should be enough to change the `"target"` in your `tsconfig.json`'s `"compilerOptions"` from `"es5"` to `"es3"`.

**Comment by ahocevar** [comment]
To improve the developer experience of this library, we should publish transpiled .js files. So I'll leave this issue open as a reminder for that. A pull request would also be welcome, if someone wants to take this on.

**Comment by pelord** [comment]
We solved it by using Babal finally.

Thanks for your support!

https://github.com/infra-geo-ouverte/igo2-lib/commit/938e2de4e18dc9588bb39949fbca6439bb4e9489
