### ISSUE TITLE
window.olms is undefined with olms.js v6.0.0

### ISSUE THREAD

**Issue by M393** [openlayers/ol-mapbox-style#253]
`window.olms` is set, but it is `undefined`.
I built the package and included ol.js (v6.1.1, downloaded from openlayer.org) and olms.js in my page. 
This works with olms v5.0.2 but not with v6.0.0.

It seems like the removed `export default` in src/olms.js causes this.

**Comment by ahocevar** [comment]
Thanks for reporting. I'm fixing this now and will publish a patch release.

**Comment by ahocevar** [comment]
New version v6.0.1 published.

**Comment by M393** [comment]
Thank you, @ahocevar it is working!
