### ISSUE TITLE
Apply & olms allways generate tiled ol sources?

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/ol-mapbox-style#257]
Is it possible to generate ol/source/Vector and not ol/source/VectorTile for geojson data source with apply and olms?

**Comment by ahocevar** [comment]
That's definitely possible. You need  `"type": "geojson"` instead of `"type": "vector"` for your source configuration in the style document. See https://unpkg.com/ol-mapbox-style@6.0.1/dist/examples/geojson.html for an example.

**Comment by AlenKelemen** [comment]
Oh, yes, my mistake, sorry.
