### ISSUE TITLE
No layer stack obedience

### ISSUE THREAD

**Issue by 1337pinter** [openlayers/ol-mapbox-style#264]
Hello, 

I use vector map as base layer, positioned at index 0, other drawings are stacked at higher indexes, despite that text from base layer is positioned at the top of other drawings.

![image](https://user-images.githubusercontent.com/30489662/77949511-5ba7bf80-72c7-11ea-8f69-c67012775ea2.png)

Any idea? I tried removing all setting of zIndexes and the problem is still there.

Thank you.

BR

**Comment by ahocevar** [comment]
This is a result of OpenLayers's canvas reuse optimisation. To avoid it, you would have to configure the base layer with a `className` property. See https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html.

**Comment by 1337pinter** [comment]
Thank you! Setting className solved the problem!

BR
