### ISSUE TITLE
ol verison and ol-mapbox-style veriosn ?

### ISSUE THREAD

**Issue by luqinghui** [openlayers/ol-mapbox-style#265]
I have vector tiles generated by GeoServer, and codes(include tile url convert function to get the tile form geowebcahe dir and render tile using the ol-mapbox-style). The code work fine. But when I rewrite it using the openlayers 6 and ol-mapbox-style, it doesn't work. 

Firstly, I found program could not get the right tile. I read the docs and found the openlayers 6 has the different TileGrid to ol5. So, I change the the tileUrlFunction to get the right tile. But it still does not work.

I try to use the openlayers 5(do not modify the code, only reinstall the openlayers 5), it work fine. So, I want to konw if ol-mapbox-style is bind to the specify openlayers version?

**Comment by ahocevar** [comment]
For each version, you can find that information in ol-mapbox-style's `package.json`. For the latest version of ol-mapbox-style, you need at least OpenLayers v6.1:

https://github.com/openlayers/ol-mapbox-style/blob/v6.1.1/package.json#L36

**Comment by luqinghui** [comment]
@ahocevar thanks, I tried the OpenLayers v6.1.1, but it still doesn't work.

**Comment by ahocevar** [comment]
In this case, can you please elaborate on what exactly does not work?

**Comment by luqinghui** [comment]
@ahocevar  I just found I made a mistake on fetching the tile, it works now 😂. Thanks.
