### ISSUE TITLE
Keep track of layers added via ol-mapbox-style

### ISSUE THREAD

**Issue by leanfucio** [openlayers/ol-mapbox-style#266]
Is there a way to track layers created? Here is the code I use to add a layer

`olms(this.map, 'path/to/style.json');`

The idea is to switch between maps. So I thought of adding an id (and z-index if possible) to that layer beforehand so that whenever I have to switch, then I could just fetch the layer by id then delete that layer then create the new map (will have an id and z-index too for another switching)

**Comment by leanfucio** [comment]
Is it also possible to add css beforehand?

**Comment by leanfucio** [comment]
I'm new to this maps and openlayers so bear with me. (Sorry I meant className, not css)

I understand what you meant and that's some info.

Another thing I wanted is to add properties (like id, z-index, className, etc.) to the layer **before** generating the layer. This way, new layers are expected to have properties and I could like, get the layer by id or className easily. Like OpenLayers addLayer:

```
var layer = new ol.layer.Tile({
    id: 'myId',
    zIndex: 2,
    className: 'myClassName'
    source: source
});
map.addLayer(layer);
```

The thing is, I only know how to add layers using (urls are from MapTiler's Cloud)
`olms(this.map, 'https://api.maptiler.com/maps/.../style.json?key=123');` or 
`apply(this.map, 'https://api.maptiler.com/maps/.../style.json?key=123');`

But both only uses a string url as the 2nd parameter. I don't know if there's another way of doing it so that it could go with additional properties (like id, z-index, className, etc.).

**Comment by ahocevar** [comment]
If you need to set more properties on the layers before they are created, it is better to create them yourself and use a lower level API, e.g. the [applyStyle](https://github.com/openlayers/ol-mapbox-style#applystyle) function.

**Comment by leanfucio** [comment]
Thanks maybe that's what I need since applyStyle uses a layer from OpenLayers.

I have a question, I image the code would be like

```
var layer = new ol.layer.Vector({
    id: 'myId',
    zIndex: 2,
    className: 'myClassName'
    source: ? // what should I put here since I only have a link for the style
});

$.get("https://api.maptiler.com/maps/.../style.json?key=123")
            .then(function(res) {
            olms.applyStyle(layer, res, "openmaptiles");
 });
```

I don't know what to put in the _source_ property because I only have a style url that will be used in the applyStyle.

**Comment by ahocevar** [comment]
This is currently a bit cumbersome, because there is no way in OpenLayers to define a vector tile source with a TileJSON url. So you have to first create a `TileJSON` source, and then configure a `VectorTile` source with the `tileGrid`, `tileUrlFunction` and `attributions` of the `TileJSON` source. You can easily get the TileJSON url from the style document, e.g.
```js
const tileJSONUrl = mapboxStyle.sources['openmaptiles'].url;

**Comment by ahocevar** [comment]
Note: I closed the issue because the follow-up discussion had nothing to do with the original title.
