### ISSUE TITLE
Any illustration for using olms in react app?

### ISSUE THREAD

**Issue by sterkhedkar** [openlayers/ol-mapbox-style#267]
I am unable to apply a mapbox style created from mapbox studio to an openlayers map implemented in my react app. 

Could you please give an example of how olms is implemented in react?

**Comment by ahocevar** [comment]
A minimal app could look something like this:

`App.js`
```js
import React from 'react';
import 'ol/ol.css';
import './App.css';
import olms from 'ol-mapbox-style';

class App extends React.Component {

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <div id="map"></div>
        </header>
      </div>
    );
  }

  componentDidMount() {
    olms('map', 'https://demo.tegola.io/styles/hot-osm.json');
  }
}

export default App;

**Comment by sterkhedkar** [comment]
Thanks A ton! It worked!

https://raw.githubusercontent.com/sterkhedkar/mapbox-styles/master/style.json

My style JSON resides on the location above. I used Mapbox studio to create the style json. This apparently does not render the map.

**Comment by ahocevar** [comment]
Looks like ol-mapbox-style cannot resolve the sprite url (`"mapbox://sprites/sumitv18/ck9mde5l600qd1iqt9y0yo3hd/19x8ymlgwclcdxxpoqgriwwlf"`) properly. That might be a bug, but it might also be an issue with the style file.

**Comment by sterkhedkar** [comment]
@ahocevar thanks for the help! 
I ended up using the MapboxGL js
