### ISSUE TITLE
coding sample to loading custom fontstack in pbf format?

### ISSUE THREAD

**Issue by tom62291** [openlayers/ol-mapbox-style#271]
Hi everyone,

Can have coding sample to loading custom fontstack in pbf format to share?

**Comment by ahocevar** [comment]
pbf fonts are not supported. You need to find the font in a web font format, e.g. woff2.

**Comment by tom62291** [comment]
so any example css or js to preload the web font in woff or woff2?

For example, how to I load the web font if my style containt "text-font:CYanHeiHK Bold"?

**Comment by ahocevar** [comment]
Just add the css for the font you intend to use, like you would with any web font on a web page.

**Comment by tom62291** [comment]
Ok thank.
