### ISSUE TITLE
Is "slice" supported?

### ISSUE THREAD

**Issue by brentfraser** [openlayers/ol-mapbox-style#286]
I'm trying to specify a "text-field" using a sub-string of a data property, something like:

"text-field": ["format", ["slice", ["get", "Point_Designation"], 5 ] ],

but I get 
`Uncaught Error: [1][0]: Unknown expression "slice". If you wanted a literal array, use ["literal", [...]].`

The spec alludes to slice: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice

Any help would be appreciated!

**Comment by ahocevar** [comment]
ol-mapbox-style uses the expression parser from Mapbox, and in the latest version the 'slice' operation is definitely supported. I think you are using it incorrectly though. Try

    "text-field": ["slice", ["get", "Point_Designation"], 5 ],

**Comment by brentfraser** [comment]
I had tried that before.  No error but it seemed to take it as literal:
![image](https://user-images.githubusercontent.com/1638313/88921435-c512ed00-d22b-11ea-8779-1922f38a0154.png)

**Comment by brentfraser** [comment]
The good news is that these work as expected:
`"text-field": "{Point_Designation}",`
`"text-field": ["format", ["downcase", ["get", "Point_Designation"] ] ],`

but so far, not slice.

**Comment by ahocevar** [comment]
Are you sure you are using the latest version? Here is a codesandbox that shows the `slice` function in action:

https://codesandbox.io/s/nervous-leavitt-vpedr?file=/data/states.json

**Comment by ahocevar** [comment]
The issue you are running to might also be build tool related. See #280.

**Comment by brentfraser** [comment]
I'm running nodeJS.    The node_modules/ol-mapbox-style.README.md shows:
```
# Changelog

## 6.1.1

* Fix version issue with @mapbox/mapbox-gl-style-spec

```
so it looks fairly recent.  It could be a [GeoMoose ](https://github.com/geomoose/gm3) (the JavaScript/OL framework I'm using) issue.

And I'll look into the build issue.  Thanks!

**Comment by brentfraser** [comment]
Oooh, an update to 6.1.2 solved the problem!  Thanks!
