### ISSUE TITLE
How to apply olms to existing map?

### ISSUE THREAD

**Issue by costales** [openlayers/ol-mapbox-style#288]
Hi,

I'm trying to use the plugin in my map (local vector tiles server) without luck.

For example, [this example works](https://codepen.io/ahocevar/pen/xLaBVV). But when I'm trying to use my map appears 2 maps. See [this example](https://codepen.io/costales/pen/mdPbgaa) (be careful there is a scroll bar and appears 1 map under the other:

![image](https://user-images.githubusercontent.com/5886786/89298089-217b6f80-d665-11ea-94f0-05e2f9d36995.png)

Please, how can apply a style to existing map without overwrite the current components, center, etc?

Thanks in advance!!

**Comment by ahocevar** [comment]
Simply reference the map, instead of the map target. In your code:
```js
olms.apply(map,
```
instead of
```js
olms.apply('map',
```

**Comment by costales** [comment]
Thank you so much @ahocevar !!
