### ISSUE TITLE
Styles do not work with pg_tileserv vector tiles 

### ISSUE THREAD

**Issue by Joonalai** [openlayers/ol-mapbox-style#289]
The style added with `applyStyle` does not work with MVT tiles provided by [pg_tileserv](https://github.com/CrunchyData/pg_tileserv). Regular Style object works just fine and the same style works with a GeoJSON source.

Below is a snippet that describes the problem with points (also tested with polygons):

```js
const style = {
      version: 8,
      name: 'test',
      metadata: {
        'maputnik:renderer': 'mbgljs'
      },
      sources: {
        populated: {
          type: 'vector'
        }
      },
      sprite: '',
      glyphs: '',
      layers: [
        {
          id: 'asd',
          type: 'circle',
          source: 'populated',
          paint: {
            'circle-color': 'rgb(42,137,134)',
            'circle-stroke-color': 'rgba(129, 40, 40, 1)',
            'circle-radius': 10
          }
        },
      ],
      id: '4yrnz1air'
    };

const style2 = new Style({
    image: new CircleStyle({
      radius: 10,
      fill: new Fill({
        color: 'rgb(42,137,134)',
      }),
    }),
  })

const layerGeojson = new VectorLayer({
  declutter: true,
  source: new VectorSource({
    format: new GeoJsonFormat(),
    url: 'https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_populated_places.geojson'
  })
});

const layerVt = new VectorTileLayer({
  source: new VectorTileSource({
     format: new MVT(),
     url: 'http://localhost:7800/public.test_layer/{z}/{x}/{y}.pbf' // Point layer
   }),
  style: style2
});

// Works
// map.addLayer(layerVt);

// Does not work 
applyStyle(layerVt, style, ['asd']).then(() => map.addLayer(layerVt));

// Works
applyStyle(layerGeojson, style, ['asd']).then(() => map.addLayer(layerGeojson));


```

I am using ol-mapbox-style==6.1.2 and ol==6.3.1.

**Comment by ahocevar** [comment]
You'll need to make sure that your vector tile source contains data that is compatible with the style you use (i.e. same attributes and geometry types).

**Comment by Joonalai** [comment]
The styles that I used for testing do not use attributes and I used the same geometry types (points and polygons) for tiles and Geojsons.

**Comment by Joonalai** [comment]
I even tried with using the exactly same layer as GeoJSON and `applyStyles` worked with it, but not with tiles.

**Comment by ahocevar** [comment]
Can you create a codepen or codesandbox that shows the issue? Including at least one tile?

**Comment by Joonalai** [comment]
Here is a working [codesandbox](https://codesandbox.io/s/openlayers-mapbox-styles-does-not-work-with-mvt-provided-by-pgtileserv-r8l6m?file=/src/index.js) from the issue. Just comment out from some of the last few lines to change the behavior.

**Comment by ahocevar** [comment]
@Joonalai Your layer definition is missing a `source-layer` property. That property has to match the layer from the vector tile, because vector tiles can contain several layers. I updated your [codesandbox](https://codesandbox.io/s/openlayers-mapbox-styles-does-not-work-with-mvt-provided-by-pgtileserv-y9un3) with the following layer property:
```json
      "source-layer": "public.osm_lodging_p",
```

**Comment by Joonalai** [comment]
Wow, thank you so much!!
