### ISSUE TITLE
Update required ol version to 6.4

### ISSUE THREAD

**Issue by M393** [openlayers/ol-mapbox-style#290]
The x-y independent scaling feature in ol 6.4 makes styles from previous versions incompatible.
See: https://github.com/openlayers/openlayers/issues/11432#issuecomment-673931464
I had the same issue and solved it by increasing the ol version in the dependencies.

**Comment by ahocevar** [comment]
Thanks for your investigations @M393. This is not caused by a version requirement, but a version mismatch caused by `ol.style.Text` not being included in the webpack configuration's `externals`.

**Comment by ahocevar** [comment]
Fixed in version 6.1.3.
