### ISSUE TITLE
mapbox json style origin/setup for own served vector tiles

### ISSUE THREAD

**Issue by elanioazul** [openlayers/ol-mapbox-style#299]
Hi,

I am having troubles when it comes to generate mapbox style json for vector tiles served from geoserver by hand so I would need a tool for doing so. 
- Maputnik is not taking for instance a group of layers as a Vector (XYZ url):
http://localhost:8080/geoserver/gwc/service/tms/1.0.0/burgos-callejero@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf
(what am I doing wrong?)
- GeoStyler seems to be prety twerked from mapbox style specification and I would prefer to use styled json and this ol-mapbox-style library.

How community get mapbox json style for their own served vector tiles? 
Thx

**Comment by ahocevar** [comment]
For thematic maps, I usually create the style by hand. For OpenStreetMap data, I use an existing style, and tweak it either by hand or with Maputnik.

**Comment by elanioazul** [comment]
thanks @ahocevar for your answer , I was fearing an answer like that..

**Comment by ahocevar** [comment]
That said, I'd really recommend checking out Mapbox Studio and their hosting offer. If you consider the hassle with doing things manually, the overall cost may well be lower when using Mapbox.
