### ISSUE TITLE
feature request : include layer id into feature properties ( vector tile )

### ISSUE THREAD

**Issue by hoogw** [openlayers/ol-mapbox-style#311]
This is not something that can be changed in OpenLayers. It has to be fixed in ol-mapbox-style. Please create a feature request issue in https://github.com/openlayers/ol-mapbox-style/.

_Originally posted by @ahocevar in https://github.com/openlayers/openlayers/issues/6752#issuecomment-744623072_

Detailed discuss, please see original post, I will not repeat here.

But this is summary what we need: 

@ahocevar  I found where the problem is

I compare with mapbox, this is a feature object in mapbox (vector tile)

                            layer: {id: "County:1/45 - 53 years of age", type: "fill", source: "esri", source-layer: "County:1", minzoom: 3.96, …}
                           properties: {_symbol: 5}
                           source: "esri"
                           sourceLayer: "County:1"
                          state: {}
                          type: "Feature"
                         _vectorTileFeature: Co {properties: {…}, extent: 4096, type: 3, _pbf: Js, _geometry: 7785, …}  

This is openlayes ,  feature object (vector tile) 
                                 
                            0: RenderFeature
                                         ends_: [14]
                                         extent_: (4) [....]
                                          flatCoordinates_: (14) [...]
                                          flatInteriorPoints_: null
                                          flatMidpoints_: null
                                          id_: undefined
                                          ol_uid: "169"
                                          properties_: {_symbol: 4, layer: "County:2"}        
                                          type_: "Polygon"
                                          __proto__: Object

You can see, that openlayers put 'layer' inside 'properties_' and only collect source-layer name. 
Mapbox, do it differently,   mapbox collect detailed info for 'layer', and you can read the layer's id, fill, color etc...

Openlayers might need improvement by include detailed info into a separated properties named 'layer'  from  feature
  Those  'layer' properties, should include all detailed info such as layer id, fill, color etc....(those info can get from root.json layer definition)         

Before openlayers fix this issue,  temp work around is get layer id by loop through root.json based on _symbol value.
You get feature.properties_._symbol is 4, then you go to root.json, loop through all layers, find the symbol value 4 and source layer "ZIP Code", then read it's id, "ZIP Code/45 - 53 years of age",

**Comment by hoogw** [comment]
For those have same need, before they get it implement, you can use work around solution: see original post

------------------
@ahocevar   

I use work around method to get it works  see [ to codesandbox](https://codesandbox.io/s/young-water-uquvh?file=/src/index.js),

when you mouse hover, at left corner, it shows age group 'ZIP Code/45 - 53 years of age' 

---------------------------------------------------------------------------------------------

**Comment by hoogw** [comment]
@ahocevar   
Can you add layer similar as mapbox? this is [mapbox's layer definition](https://docs.mapbox.com/mapbox-gl-js/api/map/#queryrenderedfeatures-returns):

                         Each feature includes top-level layer, source, and sourceLayer properties. The layer property is an object representing the style layer to which the feature belongs. Layout and paint properties in this object contain values which are fully evaluated for the given zoom level and feature.

**Comment by ahocevar** [comment]
Yes, ol-mapbox-style could set additional properties on each feature. I think this should be configurable, so it is only enabled on demand.

**Comment by hoogw** [comment]
> Yes, ol-mapbox-style could set additional properties on each feature. I think this should be configurable, so it is only enabled on demand.


Can you show some hint, how to configure it to do so? I want to try it.

**Comment by ahocevar** [comment]
In `stylefunction.js`, when a filter applies, set a custom property (e.g. `styleLayer`) on the `feature` that is passed to the stylefunction.

**Comment by hoogw** [comment]
stylefunction.js  

 I see LayerId,  this value is exactly what I want it to be included in final feature object.  

                          const layerId = layer.id;

                          mapboxLayers.push(layerId);

                           const filter = layer.filter;
      if (!filter || evaluateFilter(layerId, filter, f, zoom)) {


Your suggest make sense to me, but it is hard for me to make it work. If you can make change, then all people can benefit this feature.

**Comment by hoogw** [comment]
current feature object: 

                                         RenderFeature
                                                ends_: [22]
                                               extent_: (4) []
                                               flatCoordinates_: (22) []
                                               flatInteriorPoints_: null
                                               flatMidpoints_: null
                                               id_: undefined    // always undefined, it should be a feature id, unique id, same as ol_uid ?
                                              ol_uid: "265"       // very useful, this unique feature id. will use later to identify this feature when highlight this feature.
                                              properties_:
                                                          layer: "County:2"

                                                           // maybe add layerId ?
                                                           layerId: "County:2/45 - 53 years of age"

                                                         

                                                          _symbol: 4

                                               type_: "Polygon"


                                               // or maybe like mapbox did add separated properties named 'layer'
                                               layer: { id: xxx,  filter:....}

**Comment by ahocevar** [comment]
Implemented with #312. Please consider [sponsoring me](https://github.com/sponsors/ahocevar).

**Comment by hoogw** [comment]
I am trying to test it.  but how to update the latest change?
I have try npm install ol-mapbox-style,   does not work, it only give me old version.

I select branch as 'feature-belongs-to-layer', then don't know what to do next to get it down to my local pc, 
just download it? replace whole folder under /node_module/ol-mapbox-style ?

Will sponsor you for your quick fix for sure.

**Comment by ahocevar** [comment]
I created a tag with the updated code. Just download it as zip or tgz, and extract to node_modules/ol-mapbox-style. https://github.com/ahocevar/ol-mapbox-style/releases/tag/v6.2.2-pre

**Comment by hoogw** [comment]
not work: 

                                                    // error : feature is not defined
                                                    // var mapboxLayer = feature[0].get('mapbox-layer');


works: 

                                                    layerId = properties['mapbox-layer'].id;


full code: 
                                                    
                                                   var features = map.getFeaturesAtPixel(event.pixel);
                                                   var properties = features[0].getProperties();


                                                     console.log('feature  ', features)
                                                     console.log('properties [0] ',  properties)

                                                     // error : feature is not defined
                                                    // var mapboxLayer = feature[0].get('mapbox-layer');

                                                   if (properties['mapbox-layer']) {
                                                      layerId = properties['mapbox-layer'].id;
                                                   }

**Comment by hoogw** [comment]
I try to highlight the feature, when user hover, but failed. 

[codesandbox](https://codesandbox.io/s/sweet-river-mdjhb?file=/src/index.js)

error is 

                     selected_feature.setStyle is not a function


compare the [original hover sample](https://codesandbox.io/s/staging-sea-72335?file=/src/index.js), 


seem, feature in vector tile is different with feature in geojson, 
setStyle() is only available in geojson's feature, but not available in vector tile's feature.

**Comment by hoogw** [comment]
with 6.3.0, it works

[codesandbox sample](https://codesandbox.io/s/gallant-goldstine-dd40f?file=/src/index.js)

**Comment by hoogw** [comment]
codesandbox,  working sample:


 [ arcgis Vector tile, hover, highlight](https://codesandbox.io/s/sweet-river-mdjhb?file=/index.html)

It has problem, not stable, sometime strange thing happen, special for circle feature, not correct, not properly works


[Without hover hightlight](https://codesandbox.io/s/youthful-poincare-weo2l?file=/src/index.js), seems works fine,

**Comment by ahocevar** [comment]
The "circle" features you're looking at are MultiPoint features. This means that the 1000s of points you're seeing highlighted belong to a single feature. So that behavior is expected.

And please: don't cross post in 3 issues!

**Comment by hoogw** [comment]
Yes, sometime I see hundreds of circle highlighted which should be just one.
[This sample](https://codesandbox.io/s/sweet-river-mdjhb?file=/index.html) when you hover a point, it is very hard to identify point.  always polygon.  I use first feature,  feature[0], as selected feature, it is multipoint, show hundreds of point one second and disappear, maybe because mouse move out of circle point in next second, is that circle point too small? I can't make circle bigger, since too big will block other polygon feature.

Ideally,  should be single point, and easy hover, means hover state should stay until I move mouse out of circle point.
Current, hover circle would not stay,

stroke,  means both line and polygon border?
fill, means only polygon?
image, means only point?


                                                          
                       var selected_style = new Style({
                                                            stroke: _stroke_selected,
                                                            fill: _fill_selected,
                                                            image: _circle_selected
                                                    });




when I get multipoint, how to identify just one point, not the others?
How to make hover a image circle point stay for a while until mouse move out of circle?




                        var _circle_selected =   new Circle({
                                                      fill: _fill_selected,
                                                      stroke: _stroke_selected,
                                                      radius: 8
                                              });
