### ISSUE TITLE
Feature request - get layer ids for feature and also possible to only return single style?

### ISSUE THREAD

**Issue by vittrup88** [openlayers/ol-mapbox-style#323]
Hi,

I'm using this lib to style some of my vector tiles and would like to ask if it is possible to create a function that can take openlayers feature like the stylefunction and then return a list of layer id / names from the gl style that applies (filtering) ?

atm i have a style that will display line features in light blue when no extra data analysis should be shown and when I have data analysis on the element the styling will change to that analysis. meaning multiple layers in same gl style.
Then it would be handy to know what layer id the styling is using for other filtering like hovering a feature.

also maybe an option in apply style to only return one single style instead of all ? - not merging but only selecting the style that should be drawn at top level. if this should be impl. then the same functionality should be possible in getting the layer ids.

I have looked at extending this myself but would like to reuse as much as possible. If you could add it else might point me in the right direction?

**Comment by ahocevar** [comment]
The opposite of what you want is already possible, and I think it will solve your problem. See https://github.com/openlayers/ol-mapbox-style#recordstylelayer.

So what you do is enable style layer recording:
```js
import {recordStyleLayer} from 'ol-mapbox-style/dist/stylefunction';
recordStyleLayer(true);
```
When enabled, each feature will have an additional `mapbox-layer` property. You can use that property to decide what to do when hovering over a feature with something like this:
```js
map.on('pointermove', async e => {
  const features = await vectorTileLayer.getFeatures(e.pixel);
  if (features.length > 0 && feature[0].get('mapbox-layer') === 'analyze-me') {
    // show extra data analysis
  }
});
```

**Comment by vittrup88** [comment]
Hi @ahocevar
Just worked a bit more on this one and this really supports the usage. One thing I see is that the style might result in mulitple styles but mapbox-layer only has one value. Should this be an array ?

**Comment by ahocevar** [comment]
It *could* be an array, yes. Do you need the whole layer stack? This property was designed to provide the layer of the style that is on the top of the stack.

**Comment by vittrup88** [comment]
Well it fits my usage atm. So I think it is fine. I was just wondering if this was by purpose which it turned out to be.
I think we can close this and reopen if the usage should be supported with all layers.
If extending this maybe add the property to record to use only top style.

Thanks for your explanation!
