### ISSUE TITLE
Sprites not loading from Mapbox Vector Styles

### ISSUE THREAD

**Issue by geraldo** [openlayers/ol-mapbox-style#336]
I'm using ol-mapbox-style 6.3.2 with ol 6.5 with some custom mvt served from Tegola. Everything works fine and sprites show up when loading them using a style function with _spriteData_ and _spriteImageUrl_ parameters:

`olms.stylefunction( bus_stops, glStyle, 'bcn', undefined, spriteDataJson, './sprites.png' );`

But they don't show up when using this style function:

`olms.stylefunction( bus_stops, glStyle, 'bcn' );`

and the additional **sprite** parameter in Mapbox Style definition:

```
{
    "version": 8,
    "name": "Bus Style",
    "sources": {
	    "bcn": {
	        "type": "vector",
	        "url": "http://localhost:8080/capabilities"
	    }
	},
    "layers":
    [
		{
		    "id": "bus_station",
		    "type": "symbol",
		    "source": "bcn",
		    "source-layer": "bus_station",
		    "layout": { 
		    	"icon-image": "bus_station"
		    }
		}
	],
	"sprite": "http://localhost/buses/sprites"
}
```

Sprites are definitely accessible at https://localhost:8000/sprites with CORS header. I also tried with `"sprite": "sprites"` without success.

Network tab in developer console confirms that either _sprites.json_ nor _sprites.png_ are getting loaded. Any idea what I'm doing wrong?

**Comment by ahocevar** [comment]
That's expected. The low-level API `olms.stylefunction` requires these parameters to be set when any of your layers requires sprites. See https://www.npmjs.com/package/ol-mapbox-style/v/6.3.2#parameters-2.

To get the bus_station layer added more conveniently to your existing map, use
```js
import Map from 'ol/Map';
import olms from 'ol-mapbox-style';

const map = new Map({
// ...
});
olms(map, 'http://localhost:8000/buses/style.json').then(() => {
  // now you can access your layer
  const myLayer = map.getLayers().getArray().find(layer => layer.get('mapbox-source') === 'bcn');
});

**Comment by geraldo** [comment]
Great, `olms(map, 'bus_l66_recorregut.json')` worked out perfectly and all styles with their sprites appeared.

Thanks for your great library!
