### ISSUE TITLE
applyStyle gives parsing error on valid json data

### ISSUE THREAD

**Issue by jjarv-tuni** [openlayers/ol-mapbox-style#340]
--- error ---

Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    applyStyle index.js:157
    applyStyle index.js:152
    hTXjU index.6b9ca3e8.js:431
    promise callback*.hTXjU< main.js:44
    newRequire index.6b9ca3e8.js:71
    <anonymous> index.6b9ca3e8.js:120
    <anonymous> index.6b9ca3e8.js:143

--- end ---

-- Snippet of JSON data ---
{
  "version" : 8,
  "name" : "NLS Basemap",
  "center" : [ 21.645, 63.101 ],
  "zoom" : 11.35,
  "sources" : {
    "taustakartta" : {
      "type" : "vector",
      "url" : "https://avoin-karttakuva.maanmittauslaitos.fi/vectortiles/tilejson/taustakartta/1.0.0/taustakartta/default/v20/WGS84_Pseudo-Mercator/tilejson.json?api-key=<DND>"
    }
  },
  "glyphs" : "https://avoin-karttakuva.maanmittauslaitos.fi/vectortiles/glyphs/{fontstack}/{range}.pbf?api-key=<DND>",
  "layers" : [ {
    "id" : "background",
    "type" : "background",
    "paint" : {
      "background-color" : "#ffffff"
    }
  } ...

--- end ---

--- code ---
 
sourceTile = new VectorTileSource({
  format: new MVT({layers:['rakennus','liikenne','maastoaluereuna','poi','nimisto']}),
  url: `https://avoin-karttakuva.maanmittauslaitos.fi/vectortiles/taustakartta/wmts/1.0.0/taustakartta/default/v20/WGS84_Pseudo-Mercator/{z}/{y}/{x}.pbf?api-key=${key}`,
  maxZoom: 14
  
})

baseMMLmap = new VectorTileLayer({
  source: sourceTile,
})

const map = new Map({
  target: 'basemap',
  view: trView,
  layers: [],
});

fetch ('http://192.168.1.113/taustakartta.json')
.then (res => res.text())
.then (data => {
 
  applyStyle({glStyle: data, layer: baseMMLmap})
  

})

--- end ---

**Comment by ahocevar** [comment]
ol-mapbox-style does not support API key templates and completion. So for your URLs you need to replace `api-key=${key}` and `api-key=` with the correct API key you are going to use, e.g. `api-key=myapikey123`.

**Comment by jjarv-tuni** [comment]
Those keys are in original code but as they are not to be disclosed so I left them out of the snippet.  console.log(JSON.parse(data)) returns valid object in fetch structure but applyStyle causes error.

**Comment by ahocevar** [comment]
The signature you are using for applyStyle is incorrect. You have to call
```js
applyStyle(baseMMLmap, data, source);
```
Note that you also need to provide the source.

**Comment by jjarv-tuni** [comment]
Okay, it's clearly my mistake. In this case applyStyle(baseMMLmap,data,['rakennus','liikenne','maastoaluereuna','poi','nimisto']) did the magic. Thanks again!
