### ISSUE TITLE
Explicit es.js imports break build

### ISSUE THREAD

**Issue by ChristianKohler** [openlayers/ol-mapbox-style#342]
## Problem

In a build setup without es modules, this library doesn't work anymore with version 6.4.x (6.3.x works).

```
../node_modules/@mapbox/mapbox-gl-style-spec/dist/index.es.js:15131
    export { Color, ParsingError$1 as ParsingError, ValidationError, composite, convertFilter$1 as convertFilter, derefLayers, diffStyles as diff, expression$1 as expression, createFilter as featureFilter, format, styleFunction as function, v8 as latest, migrate, v8, validateStyle as validate, validateMapboxApiSupported, visit };
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```

It seems that importing the es module directly within the js file causes the issue:

`import {Color} from '@mapbox/mapbox-gl-style-spec/dist/index.es.js';`

## Fix

I have created a PR which fixes the above problem. See: https://github.com/openlayers/ol-mapbox-style/pull/341

**Comment by ahocevar** [comment]
Fixed with #341
