### ISSUE TITLE
ArcGIS basemap attribution disappears

### ISSUE THREAD

**Issue by ak-kemp** [openlayers/ol-mapbox-style#345]
The basemap attribution for an ArcGIS vector tile basemap completely disappears starting from zoom level 3. The attribution is required to be shown in an application per the [deployment requirements](https://developers.arcgis.com/documentation/mapping-apis-and-services/deployment/basemap-attribution/).  This behavior can be seen in the examples in the OpenLayers and ArcGIS location services guide e.g.: 

- [Get Started](https://developers.arcgis.com/openlayers/#3-quick-start)
- [Display a map](https://developers.arcgis.com/openlayers/maps/display-a-map/)

Is there anything in the code that we need to add to display the attribution at other zoom levels: 

```
     const map = new ol.Map({ target: "map" });

      map.setView(
        new ol.View({
          center: ol.proj.fromLonLat([-25, 25]), // Starting location [longitude, latitude]
          zoom: 2
        })
      );

      const apiKey = "YOUR_API_KEY";

      const basemapId = "ArcGIS:Streets";

      const basemapURL = "https://basemaps-api.arcgis.com/arcgis/rest/services/styles/" + basemapId + "?type=style&token=" + apiKey;

      olms(map, basemapURL);
```

Or, is this a bug in olms itself?

**Comment by ahocevar** [comment]
This was a bug in OpenLayers: openlayers/openlayers#11856. If you update the ol dependency to v6.7.0 (or at least v6.6.0), you'll get a fixed version.

**Comment by ak-kemp** [comment]
That works! Thanks
