### ISSUE TITLE
how to remove previous style?

### ISSUE THREAD

**Issue by sohagmahin** [openlayers/ol-mapbox-style#348]
I used multiple Mapbox styles and but when I applied another style then it overrides the previous style.
so, I want to delete the previous style, if I apply another style.
Is it possible?
N.B: I used this way to apply Mapbox style.
`  
var key = 'Your Mapbox Access Token here';  
olms('map', 'https://api.mapbox.com/styles/v1/mapbox/bright-v9?access_token=' + key);  
`

**Comment by ahocevar** [comment]
Yes, you can remove all layers that were created by `ol-mapbox-style` from the map:
```js
const layers = map.getLayers().getArray();
for (let i = layers.length - 1; i >= 0; --i) {
  if (layers[i].get('mapbox-source') {
    map.removeLayer(layers[i]);
  }
}
```
This works because ol-mapbox-style sets a `mapbox-source` property on each layer it creates.

**Comment by sohagmahin** [comment]
It works. :fire:
Thanks ❤️  @ahocevar
