### ISSUE TITLE
Couldn't get Icons from sprite to show up on the Vector Tile layer with StyleFunction.

### ISSUE THREAD

**Issue by oren-ned** [openlayers/ol-mapbox-style#352]
I am trying to add a Vector Tile data set to Open Layers as one of the base map options.
Here is the link for the Vector Tile and it is accessible (https://tiles.arcgis.com/tiles/TJH5KDher0W13Kgo/arcgis/rest/services/VectorTileTesting_112820/VectorTileServer).
when I use olms( window.map, "https://tiles.arcgis.com/tiles/TJH5KDher0W13Kgo/arcgis/rest/services/VectorTileTesting_112820/VectorTileServer/resources/styles/root.json"); it draws the Vector Tile as expected and all the icon symbols are rendered. 

**Our process requires this Vector Tile layer to be configured as a layer**: 
Using the following url parameter and the function I am getting a styled layer without sprite images.  Not sure if I am using the right function for this or have a good understanding of the parameters. Is there a document or working example that may help to get this task done?

**URL Parameter:**
  "url": "https://tiles.arcgis.com/tiles/TJH5KDher0W13Kgo/arcgis/rest/services/VectorTileTesting_112820/VectorTileServer/tile/{z}/{y}/{x}.pbf"

**FUNCTION:**
```js
export function getVectorTileLayer(url) {
  let layer = new VectorTileLayer({
    renderMode: 'vector',
    reload: Infinity,
    declutter: true,
    //extent: extent,
    source: new VectorTileSource({
      attributions: "LIO VectorTiles Test",
      format: new MVT(),
      url: url + "/tile/{z}/{y}/{x}.pbf",
      //maxZoom: 26,
      //rootPath: url + "/resources/styles/root.json",
      //spritePath: url + "/resources/sprites/sprite.json",
      //pngPath: url + "/resources/sprites/sprite.png",   
    }),
  });
  //let rootPath= url + "/tile/{z}/{y}/{x}.pbf"; // rootPath for applySytle
  let rootPath = url + "/resources/styles/root.json";
  let spritePath = url + "/resources/sprites/sprite.json";
  let pngPath = url + "/resources/sprites/sprite.png";
    fetch(rootPath).then(function(response) {
      response.json().then(function(glStyle) {
          fetch(spritePath).then(function(spriteData) {
            fetch(pngPath).then(function(spriteImageUrl) {

              stylefunction(layer, glStyle, "esri", undefined, spriteData, spriteImageUrl.url);
          
           });
        });
    });
  });
  
  return layer //StyledLayer is returned with no sprite Images;
};
```
![image](https://user-images.githubusercontent.com/10034654/140834833-1c9354e4-75ea-4ed8-a79a-be1340d1df9b.png)

Thank you for the help or any advice to solve this issue.

N.

**Comment by ahocevar** [comment]
You have to pass the decoded json as `spriteData`, not the response. Also, you are not supposed to `fetch` the sprite image (i.e. `sprite.png`). You have to pass the url (i.e. `pngPath` to `styleFunction`.  I see that the docs are misleading here. Will fix that.

Something like this should work:
```js
fetch(rootPath).then(function (response) {
  response.json().then(function (glStyle) {
    fetch(spritePath).then(function (response) {
      response.json().then(function (spriteData) {

        stylefunction(layer, glStyle, "esri", undefined, spriteData, spritePath);

      });
    });
  });
```
Also note that in the latest dev version of OpenLayers (`npm install ol@dev`), you can use the [MapboxVector](https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html) layer, which is much more straightforward to set up.

**Comment by oren-ned** [comment]
It works as suggested!  The last argument is  the **pngPath** (url + "/resources/sprites/sprite.png")  in the above example.
We will definitely look into using the MapboxVector layer option in the future!

Thanks for the clarification and the help!
N.

**Comment by larssoe74** [comment]
> Also note that in the latest dev version of OpenLayers (`npm install ol@dev`), you can use the [MapboxVector](https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html) layer, which is much more straightforward to set up.

So you would recommend NOT using olms for ArcGIS Vector Tiles and wait for the MapboxVectorLayer in the official version of OpenLayers?

**Comment by ahocevar** [comment]
No, I'm just pointing out another option. If you want the most easy way to set up a map from a Mapbox Style, use `ol-mapbox-style`'s default export, which can even create the whole OpenLayers `Map` instance for you, if you wish.

**Comment by larssoe74** [comment]
> No, I'm just pointing out another option. If you want the most easy way to set up a map from a Mapbox Style, use `ol-mapbox-style`'s default export, which can even create the whole OpenLayers `Map` instance for you, if you wish.

Thank you so much for replying Andreas!
We have a large application with OpenLayers and primarily ArcGIS Server as source. I am just having a lot of trouble adding ArcGIS Server Vector Tiles (self-hosted not arcgis.com) to OpenLayers using OLMS. 
Could you please take a quick look at this sample, where the Vector Tile Layer added with OLMS does not show in the map?
[https://jsfiddle.net/larssoe/zgpj9207/](https://jsfiddle.net/larssoe/zgpj9207/)
Alternatively: Have you tried Vector Tiles from ArcGIS Server like this one (should be public): 
[Vector Tile with esri JS API](https://bragdev3.gis.dk/arcgis/rest/services/Hosted/Multipoint_Flat/VectorTileServer?f=jsapi)

**Comment by ahocevar** [comment]
You were hit by #324, which I just fixed.
