### ISSUE TITLE
How to override font styles from mapbox style

### ISSUE THREAD

**Issue by mediafreakch** [openlayers/ol-mapbox-style#382]
I spent some time trying to figure our how to override the fonts specified in the external mapbox style.json that I use. It uses `Frutiger Neue Regular` as a font to display various text features. Obviously users seldom have that font installed. I'd like to replace this with a Roboto webfont that is already loaded on my website.

I created a short codepen to illustrate the problem: https://codesandbox.io/s/mapbox-style-forked-pn3y2

Wrong font:

![Bildschirmfoto 2021-11-22 um 15 00 33](https://user-images.githubusercontent.com/777093/142874668-b075a1fb-e0e1-4e0f-8f55-df286ed196a6.png)

Correct font (https://test.map.geo.admin.ch/):

![Bildschirmfoto 2021-11-22 um 15 00 13](https://user-images.githubusercontent.com/777093/142874582-2cc814ca-8cdf-4ede-81c9-74bf0949fd94.png)

Looking at the API one could somehow use `stylefunction()`, but then one would loose all the benefits of `olm` automatically loading the correct `.json` files and setting up the layers?! 

Is there any way to override the fonts?

**Comment by ahocevar** [comment]
Providing a font substitution table is only possible when using `ol-mapbox-style/dist/stylefunction`, as you found out already.

But the recommended way to resolve this is to make sure the fonts used by your style are available to your application as web fonts. From `README.md`:

> Only commonly available system fonts and Google Fonts will automatically be available for any text-font defined in the Mapbox Style object. It is the responsibility of the application to load other fonts.

I forked your sandbox and added the necessary web fonts: https://codesandbox.io/s/github/ahocevar/mapbox-style-frutiger/tree/main/. I downloaded the woff files and `style.css` from https://www.cufonfonts.com/font/frutiger-neue-lt, and modified `style.css` to the version you see in the `fonts/` folder of the sandbox. For using this approach in production, make sure you meet the license terms of the used fonts.

The advantage of this approach is that you get the map rendered with the correct fonts.

**Comment by mediafreakch** [comment]
Thank you for looking into this and providing an updated example! Unfortunately it seems that the licence information on cufonfonts.com is wrong. Neue Frutiger is a paid font even if you just use it on your own desktop. For the web, it is pay-per-use (pageviews).

The application I'm integrating the map with is part of a commercial service anyway. So either I'll have to use `stylefunction` directly to overwrite the fonts and build loading and parsing of the related `.json` file around it, or maybe I'll find a hack with re-assigning font-faces via styles.css.

**Comment by mediafreakch** [comment]
I managed to use Google fonts as a replacement for the fonts specified in the style.json. Here's the updated example: https://codesandbox.io/s/mapbox-style-forked-pn3y2 

The trick is to use css `@font-face` and map the Frutiger font names to a different `woff` file, the one from the Google fonts. I am aware that this is not the intention by the creator of the mapbox style and that this might skew the results.

However there's a bug in how the fonts are processed by `ol-mapbox-style` plugin. I'm gonna create a separate issue for that.
