### ISSUE TITLE
Fonts with multiple spaces in name parsed incorrectly

### ISSUE THREAD

**Issue by mediafreakch** [openlayers/ol-mapbox-style#383]
**Steps to reproduce**

1. Open https://codesandbox.io/s/mapbox-style-forked-bxd9n

Expected result: The text labels on the map should be displayed with the Roboto font (no serif)

Actual result: The text labels on the map are displayed with a default system font (serif)

**Problem description**

Seems like the following line in [`getFonts()`](https://github.com/openlayers/ol-mapbox-style/blob/main/src/index.js#L79) parses only part of the font name, thus leads to the wrong (incomplete) font name being referenced in the resulting layer style.

**Example**

The map style in the codepen contains the following font references:

- Frutiger Neue Italic
- Frutiger Neue Regular
- Frutiger Neue Condensed Medium
- Frutiger Neue Condensed Bold
- Frutiger Neue Condensed Regular

However the layer styles will finally reference the following fonts:

- Frutiger Neue
- Frutiger Neue Condensed

Of course those font names will not be in the document (unless you know about this bug and add them explicitly like that)

**Comment by ahocevar** [comment]
That's intentional. `italic` is a font style, `medium`, `bold` and `regular` are font weights.

**Comment by mediafreakch** [comment]
Good to know thanks! Guess this is coming from [mapbox-to-css-font](https://github.com/openlayers/mapbox-to-css-font)?

I just wondered if this should be documented in this plugin's README under the existing section where the special treatment of fonts is mentioned.

**Comment by ahocevar** [comment]
Yes, this comes from mapbox-to-css-font. See the example in its README:

>     var parseFont = require('mapbox-to-css-font');
>     parseFont('Open Sans Regular', 16, 1.2);
>     // returns 'normal 400 16px/1.2 "Open Sans"'

The input is "Open Sans Regular", "Regular" matches the font weight 400, so the result is 'normal **400** 16px/1.2 "Open Sans"'
