### ISSUE TITLE
Layer zIndex issue

### ISSUE THREAD

**Issue by mediafreakch** [openlayers/ol-mapbox-style#384]
**Steps to reproduce**

1. Visit the following codepen: https://codesandbox.io/s/mapbox-style-forked-u43ir
2. Zoom in and out of the Zermatt area and keep an eye on the added vector feature on top of the mapbox style map

Expected result: The feature is always displayed above (on top) of any feature of the layers from the mapbox style

Actual result: The feature is partially obfuscated by text labels from the mapbox style

![Bildschirmfoto 2021-11-23 um 14 48 32](https://user-images.githubusercontent.com/777093/143036202-f036a1eb-1b69-4538-bd1d-89e5d5f494a5.png)

Am I doing something wrong or is this a bug? I thought that specifying a zIndex on the layer or the style should suffice?

**Comment by ahocevar** [comment]
Decluttering takes all subsequent layers with the same `className` into account. In your example, simply configure the `vectorLayer` with a different `className`, e.g. `className: 'overlay'`. Updated example with that change: https://codesandbox.io/s/mapbox-style-forked-nbzyd

**Comment by mediafreakch** [comment]
Appreciate the help and insights, as always. Thank you very much!
