### ISSUE TITLE
Style gets overwritten when more than one map is used with same layer id but different style url

### ISSUE THREAD

**Issue by M393** [openlayers/ol-mapbox-style#390]
https://github.com/openlayers/ol-mapbox-style/blob/c27e16c6996eceb6edefee1c95614f1beb03dd9c/src/stylefunction.js#L360-L362

Would it be possible to cache per style url, by e. g. putting the `functionCache` and `filterCache` variables inside the styleFunction or adding the style url as part of the lookup key or is it just a bad idea to have the same ids in different styles?

**Comment by ahocevar** [comment]
#375 would be a fix for this, but I need to find some time to review it. I think a simpler solution should be possible, by caching functions and filters in the scope of the `styleFunction`.

**Comment by M393** [comment]
Thanks for the fix, @ahocevar and @mike-000.
