### ISSUE TITLE
text-opacity zoom properties not supported

### ISSUE THREAD

**Issue by stevage** [openlayers/ol-mapbox-style#40]
I'm just trying out this library, and it looks great, but there's an obvious issue with labels showing up at the wrong zooms.

Mapbox-gl-js (zoom 13):

![screenshot 2018-01-04 16 26 36](https://user-images.githubusercontent.com/678344/34551267-342cab16-f16c-11e7-9509-9eded2a85ed2.png)

ol-mapbox-style (zoom 14):

![screenshot 2018-01-04 16 26 51](https://user-images.githubusercontent.com/678344/34551268-349bc032-f16c-11e7-8280-a37a635609ee.png)

One of the layers that shouldn't be displaying (containing the churches, primary schools etc) is defined thus:

```
    {
      "id": "foi-label",
      "type": "symbol",
      "source": "VMFEAT",
      "source-layer": "foi_index_centroid",
      "filter": [
        "!in",
        "FTYPE",
        "sign",
        "care facility",
        "residential building",
        "community venue",
        "communication service"
      ],
      "layout": {
        "text-field": "{NAME_LABEL}",
        "text-size": 10,
        "text-max-width": 6
      },
      "paint": {
        "text-color": {
          "property": "FTYPE",
          "type": "categorical",
          "default": "green",
          "stops": [
            [
              "reserve",
              "green"
            ],
            [
              "education centre",
              "hsl(30, 50%, 50%)"
            ],
            [
              "place of worship",
              "hsl(30, 50%, 50%)"
            ],
            [
              "dumping ground",
              "hsl(0, 0%, 50%)"
            ],
            [
              "hospital",
              "hsl(0, 50%, 50%)"
            ]
          ]
        },
        "text-opacity": {
          "stops": [
            [
              14.5,
              0
            ],
            [
              15,
              1
            ]
          ]
        },
        "text-halo-width": 1,
        "text-halo-color": "hsla(0, 0%, 100%, 70%)"
      }
    },
```

AFAIK, using `text-opacity` like this is the recommended way to have a layer only show up above a certain zoom level in mapbox-gl-js. Is there a workaround in ol-mapbox-style, perhaps `minzoom`?

**Comment by petrsloup** [comment]
What is the advantage of the using interpolated `text-opacity` over `minzoom` (which can be defined on every layer and is not type-specific) ?

**Comment by ahocevar** [comment]
@petrsloup I don't see any. I'd definitely recommend `minzoom`.

**Comment by soberdor** [comment]
I have the same problem (using the default mapbox-bright style). Is there any recommended solution? It works great otherwise, but the labels really make it look ugly. (Of note also, some labels are displayed twice, but this might be due to the same issue)

Compare left OpenLayers, right Maputnik:
![grafik](https://user-images.githubusercontent.com/27883798/50743429-2faea300-1218-11e9-801f-1685f5f7fa7e.png)

**Comment by ahocevar** [comment]
@soberdor Looks like you are not making use of the `declutter` option of `ol/layer/VectorTile`. What was your code to generate the above map?

**Comment by soberdor** [comment]
Thanks for your very quick reply! You were right, that option was missing, it looks much better now!

I used the code from the example on OpenMapTiles.org (https://openmaptiles.org/docs/website/openlayers/), so maybe it would be beneficial to add this line there as well for it to work out-of-the-box.

Another question, I realize that on mobile Safari the rendering gets stuck after a few interactions (zooming, moving), and only a page refresh helps. Probably a js error occurs, but I currently can't debug iOS. Do you know anything about this behavior or possible reasons?

**Comment by ahocevar** [comment]
I have submitted a pull request to update the OpenLayers example on the openmaptiles.org site: openmaptiles/www.openmaptiles.org#35
