### ISSUE TITLE
IE11 vector tile problem

### ISSUE THREAD

**Issue by tds4u** [openlayers/ol-mapbox-style#42]
When using IE11 (unfortunately still used in many companies) the code for vector tiles is not working. Even the example crashed with exception "symbol undefined".
Is there a possibility that someone can look at it and fix it if possible?

https://rawgit.com/boundlessgeo/ol-mapbox-style/v2.10.1/example/tilejson-vectortile.html
![image](https://user-images.githubusercontent.com/5459443/35327257-73a53a82-00f9-11e8-8d6e-70f6bcbde754.png)

Addtional for older browsers:
Uncaught exception: TypeError: 'inputs[Symbol.iterator]' is not a function
```
Error thrown at line 1118, column 9 in <anonymous function: module.exports>(output) in http://www.example.com/modules/maps/js/olms.js:
    throw _iteratorError;
called from line 771, column 8 in createFunction(parameters, propertySpec) in http://www.example.com/modules/maps/js/olms.js:
    parameters = extend({}, parameters);
called from line 2018, column 8 in convertToFunctions(properties, type) in http://www.example.com/modules/maps/js/olms.js:
    properties[property] = (0, _function2.default)(value, {
called from line 2072, column 6 in preprocess(layer, fonts) in http://www.example.com/modules/maps/js/olms.js:
    convertToFunctions(layer.paint, 'interpolated');
called from line 1635, column 8 in <anonymous function: exports.default>(olLayer, glStyle, source, resolutions, spriteData, spriteImageUrl, fonts) in http://www.example.com/modules/maps/js/olms.js:
    preprocess(layer, fonts);
called from line 237, column 9 in onChange() in http://www.example.com/modules/maps/js/olms.js:
    style = (0, _mapboxToOlStyle2.default)(layer, glStyle, source, undefined, spriteData, spriteImageUrl, availableFonts);
called from line 225, column 12 in <anonymous function: xhr.onerror>() in http://www.example.com/modules/maps/js/olms.js:
    onChange();
```

**Comment by bjornharrtell** [comment]
I've got a patch for it, but it's not good enough for PR as it forces IE11 as a target which may or may not be what is wanted.. in your case it may be what you want :) See https://github.com/boundlessgeo/ol-mapbox-style/compare/master...bjornharrtell:ie11

**Comment by ahocevar** [comment]
Adding a Symbol polyfill should also fix the issue. The examples add polyfills already, so you could just change the line in the html to
```html
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol"></script>
```
A pull request which changes that in all exmaples would be welcome.

**Comment by tds4u** [comment]
Added "Symbol" but now another error (translated from german). Search for "},{}],6:[function(require,module,exports){" to find right line.
Object does not support property or method "undefined"

```
                _iterator.return();
            }
        } finally {
            if (_didIteratorError) {
                throw _iteratorError;    <<<=== error
            }
        }
    }

    return output;
};

},{}],6:[function(require,module,exports){
'use strict';
```

**Comment by ahocevar** [comment]
Ok, then you also need the Symbol.iterator polyfill:
```js
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol,Symbol.iterator"></script>
```

**Comment by tds4u** [comment]
Didn't work => "Object expected"

**Comment by bjornharrtell** [comment]
Apparently "Promise,Symbol,Array.prototype.@@iterator" works.

**Comment by tds4u** [comment]
@bjornharrtell That worked !!! Thanks
@ahocevar Can you tell us how?

**Comment by bjornharrtell** [comment]
Done at https://github.com/boundlessgeo/ol-mapbox-style/pull/43 but only for the example in question. Will need to revisit later if want to have the same polyfill for all examples.

**Comment by ahocevar** [comment]
@tds4u Use the [ol](https://npmjs.com/package/ol) package and follow the instructions there. I prefer the Webpack & Uglify method. When targeting IE11, it may be better to use babel-minify instead of Uglify, since you'll be using Babel anyway.
