### ISSUE TITLE
olms not properly reading tiles property of Esri VectorTileServer definition

### ISSUE THREAD

**Issue by shawncrawley** [openlayers/ol-mapbox-style#445]
I was hoping to post this in a Q&A forum rather than as a ticket (in case the issue is me), but I thought it might easily get lost in, say, stackexchange or stackoverflow. This seems like it should be so simple, yet I've been stumped on it for days now. I'm just trying to add an Esri-defined MapBox style definition as a layer on an OpenLayers map. Here's what I've essentially got:

main.html
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/css/ol.css" type="text/css">
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/build/ol.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ol-mapbox-style@6.8.3/dist/olms.js"></script>
<div id="map" class="map" style="height:500px; width:100%"></div>
```
main.js
```javascript
olms('map', 'https://www.arcgis.com/sharing/rest/content/items/2afe5b807fa74006be6363fd243ffb30/resources/styles/root.json')
```
I end up getting a `failed to load resource: https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/tile/0/0/0.pbf` in my Console. I'm not surprised, since the actual tiles are served at `https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/0/0/0.pbf`. The URL that olms is composing and fetching under the covers is dropping `VectorTileServer` out of the URL.

I've also tried building up the OpenLayers layer myself, and then using `olms.stylefunction`. While this is mostly working, it looks like the sprites are not being fetched properly: the ".png" is not being appended to the fetch. Essentially, no matter what I try there seems to be a shortcoming.

**Comment by ahocevar** [comment]
Esri's Mapbox style and TileJSON objects have a strange way of specifying relative urls. As a workaround, you may want to try OpenLayers's `ol/layer/MapboxVector` instead, or modify the URLs in the style json before using it in ol-mapbox-style.

You are correct, this is an issue in ol-mapbox-style, and I think the best way to solve this would be something like the [`transformRequest` option](https://github.com/mapbox/mapbox-gl-js/pull/9225#issuecomment-578089885) in mapbox-gl-js.

**Comment by shawncrawley** [comment]
After some further digging/reading, I came to a solution that works using `olms.stylefunction` with my own pre-processing and finagling to come up with the appropriate arguments:

```javascript
var styleUrl = 'https://www.arcgis.com/sharing/rest/content/items/2afe5b807fa74006be6363fd243ffb30/resources/styles/root.json';
var basemapLayer = new ol.layer.VectorTile({
  declutter: true,
  opacity: opacity,
  visible: false
});
$.get(styleUrl, function (mapBoxSpec) {
  var serviceUrl = mapBoxSpec.sources.esri.url;
  var servicePromise = $.get(serviceUrl);
  servicePromise.done(function (serviceInfo) {
    basemapLayer.setSource(new ol.source.VectorTile({
        url: serviceUrl + '/' + serviceInfo.tiles[0],
        format: new ol.format.MVT()
    }));
    var resolutions = [];
    serviceInfo.tileInfo.lods.forEach(function (lod) {
      resolutions.push(lod.resolution);
    });
    $.get(mapBoxSpec.sprite + '.json', function (spriteData) {
      olms.stylefunction(basemapLayer, mapBoxSpec, "esri", resolutions, spriteData, mapBoxSpec.sprite + '.png');
    });
  });
});
```

Hopefully this can help someone else in my same situation in the future. At this point, I'm just exploring a way to use the `getFonts` argument to dynamically load the fonts required by the Mapbox Style... I'm definitely interested if anyone has experience therein.

**Comment by ahocevar** [comment]
The `transformRequest` option was added with #504. The same pull request also improves relative url handling, which should make working with Esri styles easier.
