### ISSUE TITLE
iconImages from spritesheet do not show

### ISSUE THREAD

**Issue by kad-velsl** [openlayers/ol-mapbox-style#457]
We have an angular viewer application using:
    "ol": "6.9.0",
    "ol-mapbox-style": "6.4.1",

For de icon images and pattern fills we use a spritesheet. The pattern fills worked fine but the icon images did not show. 

I compared the styles output of the styleFunction of ol-mapbox-style with the styles of OpenLayer and remarked that there was a difference in the icon image scale properties. Adding iconImg.setScale([1,1]) in the  ol-mapbox-style code did the trick: The icons were shown on the map. 

![image](https://user-images.githubusercontent.com/9080474/152378998-2bead971-9245-4b78-9121-3c0fae87290f.png)

Regards Linda

**Comment by ahocevar** [comment]
Could it be that your `sprite.json` is missing a `pixelRatio` property for the icon in question?

**Comment by kad-velsl** [comment]
The pixelRatio in the sprite.json was indeed missing. After adding this property the symbols show on the map!

Thank you for your quick response, this helps us a lot!
