### ISSUE TITLE
olms in vanilla javascript

### ISSUE THREAD

**Issue by MannusEtten** [openlayers/ol-mapbox-style#458]
i do have a project without a building tool like webpack or so, so no npm-packages.
i can use the olms to create a map. But how can i now include applyStyle so my vector tile layer in OpenLayers will be styled?
in vanilla javascript i cant use 'import stylefunction from 'ol-mapbox-style/dist/stylefunction';

**Comment by ahocevar** [comment]
How are you including the ol-mapbox-dependency then? The dist folder with the types is created by `npm run build`, the sources are in `src/stylefunction.js`. The latter you can only use in a typescript project when the `"compilerOptions"` of your `tsconfig.json` include `"allowJs": true`.

And allow me add that using typescript in a project that does not use npm is a strange setup.

**Comment by ahocevar** [comment]
Or are you using the single file build (`<script src="https://unpkg.com/ol-mapbox-style@6.8.3/dist/olms.js"></script>` or simliar? Then you'll have acess to `stylefunction` with `olms.stylefunction()`. And you'll also need `"allowJs": true`.

**Comment by MannusEtten** [comment]
the hint to use olms.stylefunction was the solution for me, thanks a lot!
Now is the question, I have to use on this moment unfortunately OL 4.6.4, I can find the 2.x -distribution which will work for this version of OL. Does this one also already have the olms.stylefunction()?

**Comment by ahocevar** [comment]
Yes, v2.11.2 has the same structure and provides `olms.stylefunction()`.

**Comment by MannusEtten** [comment]
oh i will try that one! if i use olms(map, url) how do i can show my layer on top of the basemap now?
I do have vector basemap but my vector tile layer is shown under it and not visible :-(

**Comment by ahocevar** [comment]
Just make sure your base layer is added to the map before you call `olms(map, url)`

**Comment by MannusEtten** [comment]
could you check my example at: https://www.therightdirectionserver.nl/pim/vectortiling_coolmaps.html the see where i went wrong with it?

**Comment by MannusEtten** [comment]
![image](https://user-images.githubusercontent.com/47241453/152766609-63ff8348-03ac-4825-bcf1-8b217251c91d.png)
i have put ol 4.6.4 as what we use in production together with olms 2.10.4. The vector tile layer is drawn but only in the default blue. "olms.stylefunction is not a function"

      const osmLayer = new ol.layer.Tile({source: new ol.source.OSM()})
      var bouwTekening2  = new ol.layer.VectorTile({
        source: new ol.source.VectorTile({
          format: new ol.format.MVT(),
          url: 'https://tiles.arcgis.com/tiles/v16XTZeIhHAZEpwh/arcgis/rest/services/bouwtekening2/VectorTileServer/tile/{z}/{y}/{x}.pbf'
        })
      });
      var sMap = new ol.Map({
        target: 'standardMap',
        view: new ol.View({
          center:  ol.proj.fromLonLat([6.569904,53.197413]),
          zoom: 20,
        }),
        layers: [osmLayer, bouwTekening2]
      });


      var layer = sMap.getLayers().getArray()[1];
      var url =
      "https://tiles.arcgis.com/tiles/v16XTZeIhHAZEpwh/arcgis/rest/services/bouwtekening2/VectorTileServer/resources/styles/root.json"
//  "https://www.arcgis.com/sharing/rest/content/items/f978ef64ed0049e684217cb3e35baa93/resources/styles/root.json";
fetch(url).then(function(response) {
  response.json().then(function(glStyle) {
    olms.stylefunction(layer, glStyle, "esri");
  });
});

what do i do wrong here?

**Comment by ahocevar** [comment]
v2.10.4 does not have `olms.stylefunction`, but like I said, v2.11.2 does.

**Comment by MannusEtten** [comment]
![image](https://user-images.githubusercontent.com/47241453/152932048-b60e7fa9-da72-45f8-918c-2b369f612c18.png)
i used the 2.11.2 and then those issues arise unfortunately :-(

https://www.therightdirectionserver.nl/pim/vectortiling2.html

**Comment by ahocevar** [comment]
Can't you upgrade to newer versions? That's a simple exmaple. Nothing will break if you upgrade to the latest of `ol` and `ol-mapbox-style`: https://codepen.io/ahocevar/pen/rNYjKPj

**Comment by MannusEtten** [comment]
https://www.therightdirectionserver.nl/pim/vectortiling2.html

i get it running on 4.6.5, no because OL 6.x has quit some breaking changes and we have to check our whole product to see where it breaks if we upgrade to newer version of OL.

interesting detail is that it works on the debug-version of OL.js 4.6.5 but not the minified version.

Now I only have the issue left with the tile layer disappering behind the basemap, but already thanks for your effort!

**Comment by ahocevar** [comment]
> interesting detail is that it works on the debug-version of OL.js 4.6.5 but not the minified version.

That's not so surprising, because ol-mapbox-style uses the non-API `getFlatMidpoint()` and `getFlatMidpoints()` methods for (Multi)LineString geometries, which is only available in `ol-debug.js`.
