### ISSUE TITLE
Can't get a basic working sample with an inline style

### ISSUE THREAD

**Issue by capooti** [openlayers/ol-mapbox-style#499]
Hi, first thanks for the great project. I have a vector tiles viewer based on OpenLayers, and it works well. Now I am considering to different options to use styles within the viewer.
I am struggling to have a working sample with ol-mapbox-style.

This is my basic attempt:

```
   const glStyle = {
        version: 8,
        name: "test",
        sources: {
          mylayer: {
            type: "vector"
          }
        },
        layers: [
          {
            id: "mylayer",
            type: "circle",
            source: "mylayer",
            paint: {
              "circle-color": "rgb(42,137,134)",
              "circle-stroke-color": "rgba(129, 40, 40, 1)",
              "circle-radius": 10
            }
          }
        ],
        id: "test-style"
      };

      const vectorTileLayer = new VectorTileLayer({
        source: new VectorTile({
          format: new MVT(),
          url: url_endpoint,
          tileLoadFunction: tileLoader,
        }),
        visible: True,
      })
      
      // applyStyle(vectorTileLayer, glStyle, "mylayer");
      // vectorTileLayer.setStyle(stylefunction(vectorTileLayer, glStyle, 'mylayer'));
      stylefunction(vectorTileLayer, glStyle, 'mylayer');
```

Unfortunately the layer is not rendered if I use any of the lines at the end. If I remove all of them, then the layer is correctly displayed with the default style.
I am using ol@6.13.0 and ol-mapbox-style@7.1.1
Any idea what is wrong in my code/style? Many thanks in advance

**Comment by ahocevar** [comment]
For the Mapbox source type "vector", your layer needs to reference a "sourceLayer", which is the value of the property "layer" in your (Render)Feature.

**Comment by capooti** [comment]
it worked, many thanks @ahocevar !!!
