### ISSUE TITLE
Using symbol with icon-image to render a layer created programmatically with stylefunction doesn't seem to work

### ISSUE THREAD

**Issue by capooti** [openlayers/ol-mapbox-style#500]
I am trying to apply a style with type "symbol" and with a "icon-image" to a layer created programmatically using stylefunction. The layer is correctly displayed with the default symbol or using a style with "circle". In the below code myStyle with icon-image was created based on the geojson-inline.html example.

Unfortunately the layer isn't rendered, so I am wondering if this is expected or the way I am using it is incorrect.

Many thanks again for the great project!

```
const vectorTileLayer = new VectorTileLayer({
        source: new VectorTile({
          format: new MVT(),
          url: url_endpoint,
          tileLoadFunction: tileLoader,
        }),
        visible: true,
      });

      const myStyle = {
        "version": 8,
        "id": "simple-symbol",
        "name": "simple-symbol",
        "sprite": "/assets/mb/sprites",
        "sources": {
            "mylayer": {
                "type": "vector"
            }
        },
        "layers": [
            {
                "id": "mylayer",
                "type": "symbol",
                "source": "mylayer",
                "source-layer": "default",
                "layout": {
                    "icon-image": "amenity_firestation"
                }
            }
        ],
    };

      stylefunction(
          vectorTileLayer,
          myStyle,
          "mylayer"
        );
```

**Comment by ahocevar** [comment]
When using sprites, you need to pass `spriteData` as 5th argument to `stylefunction()`. Or use a higher level API, like `applyStyle()`

**Comment by capooti** [comment]
using applyStyle did it! 
Thanks again @ahocevar and sorry for my really basic questions, I am unfamiliar with the MapBox ecosystem and I should really take time to study the style specification and the source code of ol-mapbox-style
I would need a way to provide to openlayers the styles via JSON - which would be stored in a database. I don't want to reinvent the wheel, that is why I was looking at this great project. Still unsure if I should rather implement something from scratch, as I need very basic stuff if compared with all the things which MapBox styles do.
