### ISSUE TITLE
arcgis vector tile must enforce ?f=pjson other wise will fail to load

### ISSUE THREAD

**Issue by hoogw** [openlayers/ol-mapbox-style#529]
ESRI  have 2 kind of place for vector tile:

1) at arcgis.com
           for example: 
            https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Microsoft_Building_Footprints/VectorTileServer
           default format is json
          which works

               `olms( map,    "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/styles/root.json"  );`

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Microsoft_Building_Footprints+%28+VectorTileServer+%29+&center_lat=42.36049978477919&center_long=-71.05959999999999&center_zoom=17&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FMicrosoft_Building_Footprints%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Microsoft_Building_Footprints+%28+VectorTileServer+%29+&center_lat=42.36049978477919&center_long=-71.05959999999999&center_zoom=17&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FMicrosoft_Building_Footprints%2FVectorTileServer)

<img width="2750" alt="openlayer_error1" src="https://user-images.githubusercontent.com/419582/162630732-cf7d5543-e723-4707-9831-a0931c5a8ad3.png">

   
2) at third party arcgis server in "hosted" folder
        for example:  
                         https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer
       default format is html
      which broken

               `olms( map,    "https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer/resources/styles/root.json"  );`

     [https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66339980056587&center_long=-116.31&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66339980056587&center_long=-116.31&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer)

     if you look at chrome developer tool, network tab,  this url default output is html, which cause down stream error
     I think this URL call initiated by this ol-mapbox-style, I have no way to fix, you must fix inside this library code. 

<img width="2080" alt="openlayer_error2" src="https://user-images.githubusercontent.com/419582/162631036-8d922604-da53-4c32-a7fd-e650dd92ca9e.png">

       must add ?f=pjson or ?f=json to enforce json format at this library. 

I use v7.1.1.    please fix this bug. 
v8.0.3 is not compatible with my code.  so not use.

**Comment by ahocevar** [comment]
In v8, you could use the `transformRequest` option. I *think* v8 will also work with OpenLayers versions older than v6.13, but I have not tried.

That said, if you're stuck with v7, you can try to prepend the following code:
```js
const originalFetch = fetch;
window.fetch = function(url, options) {
  const headers = options.headers || {};
  if (!headers['Accept']) {
    headers['Accept'] = 'application/json';
  }
  options.headers = headers;
  return originalFetch(url, options);
}

**Comment by hoogw** [comment]
I update to v8.0.3.   but not sure how to write transformRequest option,

API does not say it.  
  apply( map,     _rootJson_url,   "transformRequest option" );

<img width="1573" alt="Screen Shot 2022-04-10 at 11 20 43 AM" src="https://user-images.githubusercontent.com/419582/162633833-9409f241-a14e-45c9-a8c4-8cf96db686a4.png">

**Comment by ahocevar** [comment]
Something like this:
```
apply(
  map, _rootjson_url, {
    transformRequest(url) {
      return new Request(url, {headers: {Accept: 'application/json'}});
    },
  }

**Comment by hoogw** [comment]
Not working, same error,     
because I must explicitly define ?f=json at end of URL to be able to make it work, only set header.   headers: {Accept: 'application/json' does not trigger arcgis server output json. 

Only way to trigger arcgis server to output json is to add "?f=json" at the end of URL

For example: 

           https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer
         
 will give you html


Next example: 

          https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer?f=pjson

 will give you json( which is I want )

<img width="801" alt="Screen Shot 2022-04-10 at 11 36 46 AM" src="https://user-images.githubusercontent.com/419582/162634448-8be09bb5-286e-4624-bf20-3d079b2222d7.png">

**Comment by hoogw** [comment]
// works, because "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer" will return json 
                                     apply( map,    "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/styles/root.json"  );


                                      // not works, because "https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer" will return HTML, not json. 
                                      apply( map,    "https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer/resources/styles/root.json"  );

                                      //In order to work, must add '?f=json' at the end of URL  
                                      // like this: https://gis.la-quinta.org/arcgis/rest/services/Hosted/ParcelZoning/VectorTileServer?f=pjson

                                      // style root.json url have no change. 
<img width="1516" alt="Screen Shot 2022-04-10 at 11 46 31 AM" src="https://user-images.githubusercontent.com/419582/162634842-395c5728-c9cb-41bd-bf2a-d8dd9c3fc079.png">

**Comment by hoogw** [comment]
still same error,
<img width="1075" alt="Screen Shot 2022-04-10 at 11 58 26 AM" src="https://user-images.githubusercontent.com/419582/162635310-b2daf2e9-942d-437a-92f6-ef047ec0a57f.png">
<img width="1775" alt="Screen Shot 2022-04-10 at 11 59 42 AM" src="https://user-images.githubusercontent.com/419582/162635348-f4912d24-aba5-4683-bbe0-2c03a455233a.png">
<img width="2255" alt="Screen Shot 2022-04-10 at 12 00 19 PM" src="https://user-images.githubusercontent.com/419582/162635367-c7c69bae-4cfe-4686-964a-43f222ad0b2a.png">

**Comment by hoogw** [comment]
try these arcgis.com vector tile server sample

choose 'open layers'

[https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=77&select_layer=-1](https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=77&select_layer=-1)

<img width="2151" alt="Screen Shot 2022-04-10 at 12 09 47 PM" src="https://user-images.githubusercontent.com/419582/162635768-fb904326-693b-432c-8197-13513baecef6.png">

**Comment by ahocevar** [comment]
Published v8.0.4, which sends an `Accept: application/json` header with all requests for JSONs. So that should fix the problem, even without a `transformRequest` function.

**Comment by ahocevar** [comment]
If Esri does not send JSON when `Accept: application/json` is set, then it's clearly a server bug on their end. To work around it, you'll need a different `transformRequest` setup:
```js
apply(
  map, _rootjson_url, {
    transformRequest(url) {
      if (url.endsWith('.json')) {
        const modifiedUrl = new URL(url);
        modifiedUrl.searchParams.append('f', 'json');
        return new Request(modifiedUrl);
     }
  }
)
```

**Comment by hoogw** [comment]
try v8.0.4,  same error, 
the problem is when you send request like  ' ......./VectorTileServer',  you want add extra "?f=json" to the end to enforce arcgis server output json format. 
<img width="2230" alt="Screen Shot 2022-04-10 at 12 47 37 PM" src="https://user-images.githubusercontent.com/419582/162637049-b3e6824b-d888-436e-b15b-6756f3fcf546.png">

**Comment by hoogw** [comment]
v8.0.4  code used.

<img width="878" alt="Screen Shot 2022-04-10 at 12 49 09 PM" src="https://user-images.githubusercontent.com/419582/162637082-8702cb0c-a0e6-4463-91da-1c39df398336.png">

**Comment by ahocevar** [comment]
See my https://github.com/openlayers/ol-mapbox-style/issues/529#issuecomment-1094356425

**Comment by hoogw** [comment]
Finally working !!!!! with v8.0.4


<img width="2425" alt="Screen Shot 2022-04-10 at 12 55 47 PM" src="https://user-images.githubusercontent.com/419582/162637344-87c552f1-fad9-4472-a118-ba3061f0e3a1.png">

this is working code for v8.0.4 with transformRequest applied 


<img width="1604" alt="Screen Shot 2022-04-10 at 12 57 45 PM" src="https://user-images.githubusercontent.com/419582/162637409-1d3b47e2-a11b-4f3f-bb9c-161a43277ce3.png">

I will post the link on production tomorrow, so you can the result.

**Comment by hoogw** [comment]
This final production working:
[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.674447844698506&center_long=-116.29896965586569&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer&overlayOpacity=5](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.674447844698506&center_long=-116.29896965586569&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer&overlayOpacity=5) 
<img width="2854" alt="Screen Shot 2022-04-11 at 8 10 20 AM" src="https://user-images.githubusercontent.com/419582/162771152-4c0ad891-9b9c-4a7d-b9ff-d567d68c0ae1.png">
