### ISSUE TITLE
path for pbf, sometimes incorrectly at v8

### ISSUE THREAD

**Issue by hoogw** [openlayers/ol-mapbox-style#531]
v6.9.0. children map working partially, if you refresh browser, it will work with error

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Esri_Childrens_Map+%28+VectorTileServer+%29+&center_lat=42.385390918186744&center_long=-70.95047687782841&center_zoom=9.739485273944846&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FEsri_Childrens_Map%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Esri_Childrens_Map+%28+VectorTileServer+%29+&center_lat=42.385390918186744&center_long=-70.95047687782841&center_zoom=9.739485273944846&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FEsri_Childrens_Map%2FVectorTileServer)

<img width="3143" alt="Screen Shot 2022-04-10 at 1 12 18 PM" src="https://user-images.githubusercontent.com/419582/162637975-152307a7-39f5-4a76-b9e4-43a53f38259a.png">

v7 and v8, children map pbf path incorrectly 

<img width="2941" alt="Screen Shot 2022-04-10 at 1 15 49 PM" src="https://user-images.githubusercontent.com/419582/162638175-71c0437c-5d2f-4edb-9372-3a26ad061984.png">

this is v6.9.0 with correct pbf path
<img width="3176" alt="Screen Shot 2022-04-10 at 1 19 45 PM" src="https://user-images.githubusercontent.com/419582/162638250-966c12f0-f8b4-448a-85c8-b0c4527cc76c.png">

try this link

[https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=41&select_layer=-1](https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=41&select_layer=-1)

<img width="1966" alt="Screen Shot 2022-04-10 at 1 22 56 PM" src="https://user-images.githubusercontent.com/419582/162638425-60cd2990-c413-4143-8970-e38a1bec2830.png">

**Comment by ahocevar** [comment]
For this, you also need `transformRequest`, because ArcGIS Server uses incorrect relative URLs. This is a known problem. See this example: https://github.com/openlayers/ol-mapbox-style/blob/8b9c80b713fdfea10614b48a33a582fcb64384aa/examples/esri-transformrequest.js.

**Comment by ahocevar** [comment]
Explanation: in v6, this worked by chance, because of a bug in ol-mapbox-style. The problem is that the TileJSON document (https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/) contains an incorrect `tiles` entry:
```json
    "tiles": [
        "/tile/{z}/{y}/{x}.pbf"
    ]
```

The url in there resolves to https://tiles.arcgis.com/tile/{z}/{y}/{x}.pbf, because it starts with a `/`, which means it is a complete path, not a relative url. If the `tiles` entry was
```json
    "tiles": [
        "./tile/{z}/{y}/{x}.pbf"
    ]
```
it would work correctly. But the way things are, you'll need `transformRequest` again to fix the path.

**Comment by hoogw** [comment]
fixed.  try it.


[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Esri_Childrens_Map+%28+VectorTileServer+%29+&center_lat=27.204792882187263&center_long=-74.43576810443855&center_zoom=4.114395482148916&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FEsri_Childrens_Map%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=Esri_Childrens_Map+%28+VectorTileServer+%29+&center_lat=27.204792882187263&center_long=-74.43576810443855&center_zoom=4.114395482148916&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2FEsri_Childrens_Map%2FVectorTileServer)
<img width="2484" alt="Screen Shot 2022-04-11 at 2 45 25 PM" src="https://user-images.githubusercontent.com/419582/162838749-e7220df0-6674-4cf1-bca5-12d3fbcf6644.png">



This is updated code.

<img width="1131" alt="Screen Shot 2022-04-11 at 2 46 29 PM" src="https://user-images.githubusercontent.com/419582/162838853-11e57306-5631-439a-ae4f-1ee218a00c26.png">
