### ISSUE TITLE
getLayer failed on v8, but work on v6, v7

### ISSUE THREAD

**Issue by hoogw** [openlayers/ol-mapbox-style#536]
By update to v8,  failed to change opacity, it works before with v6, v7
look the error, seems getLayer failed on v8, but work on v6, v7

v6, I use 'olms' , when upgrade to v8, I use 'apply', 

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.674447844698506&center_long=-116.29896965586569&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.674447844698506&center_long=-116.29896965586569&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer)

<img width="2854" alt="Screen Shot 2022-04-11 at 8 10 20 AM" src="https://user-images.githubusercontent.com/419582/162770378-5a0f61ed-def7-4cf2-84e6-8210c583df92.png">

<img width="959" alt="Screen Shot 2022-04-11 at 8 12 41 AM" src="https://user-images.githubusercontent.com/419582/162770664-71c1d3ff-bd2d-4e8f-be46-0876224681e3.png">

**Comment by hoogw** [comment]
different sample show different error when change opacity

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=2020_USA_Population_Growth_VTPK+%28+VectorTileServer+%29+&center_lat=42.36049978477919&center_long=-71.0596&center_zoom=17&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2F2020_USA_Population_Growth_VTPK%2FVectorTileServer&overlayOpacity=4](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=2020_USA_Population_Growth_VTPK+%28+VectorTileServer+%29+&center_lat=42.36049978477919&center_long=-71.0596&center_zoom=17&url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices%2F2020_USA_Population_Growth_VTPK%2FVectorTileServer&overlayOpacity=4)
<img width="2623" alt="Screen Shot 2022-04-11 at 8 19 02 AM" src="https://user-images.githubusercontent.com/419582/162772094-41fadb41-ced6-4507-8e32-9c402034f7f3.png">


You can try more sample, hosted on arcgis.com

[https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=50&select_layer=-1](https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Ftiles.arcgis.com%2Ftiles%2FP3ePLMYs2RVChkJx%2Farcgis%2Frest%2Fservices&org=arcgis+vector+tile+server+sample&_center_lat=42.3605&_center_long=-71.0596&_center_zoom=17&select_folder=50&select_layer=-1)


You can try more sample,  hosted on third-party arcgis-server

[http://localhost:10/json2tree/esri/server/folder.html?url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices&org=La+Quinta+CA&_center_lat=33.6634&_center_long=-116.31&_center_zoom=17&select_folder=13&select_layer=-1](http://localhost:10/json2tree/esri/server/folder.html?url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices&org=La+Quinta+CA&_center_lat=33.6634&_center_long=-116.31&_center_zoom=17&select_folder=13&select_layer=-1)

**Comment by ahocevar** [comment]
Your imports are incorrect:
```js
                    import apply from 'ol-mapbox-style';
                    import {applyStyle} from 'ol-mapbox-style';
                    import getLayer from 'ol-mapbox-style';
                    import getLayers from 'ol-mapbox-style';
```
This means that `apply`, `getLayer` and `getLayers` are all assigned the default import. Instead, you'll want to use
```js
                    import apply from 'ol-mapbox-style';
                    import {applyStyle, getLayer, getLayers} from 'ol-mapbox-style';
```

**Comment by hoogw** [comment]
Fixed.

This vector tile is on third party arcgis server, not on esri arcgis.com, different.  try it.

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.67444775868565&center_long=-116.29896965586568&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer&overlayOpacity=4](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.67444775868565&center_long=-116.29896965586568&center_zoom=17.606760329604707&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer&overlayOpacity=4)


<img width="1919" alt="Screen Shot 2022-04-11 at 2 58 11 PM" src="https://user-images.githubusercontent.com/419582/162840371-f76365b3-2758-4b88-b6a7-09a3192a29d9.png">



this is the change
<img width="835" alt="Screen Shot 2022-04-11 at 2 59 17 PM" src="https://user-images.githubusercontent.com/419582/162840502-edc11258-9ba6-4251-8d0a-056e2e24a596.png">
