### ISSUE TITLE
Crashes with an error - Uncaught TypeError: __webpack_require__.r is not a function

### ISSUE THREAD

**Issue by supervueman** [openlayers/ol-mapbox-style#539]
Hello, please help. What could be the problem? I connect this package and get the following error.
![image](https://user-images.githubusercontent.com/27947580/164390701-6e888ae9-e5ba-4c3d-bf62-346246d82e5f.png)

I use: 
Node js 14.16.1
Vue js 2.6.11
ol: 6.14.1
ol-mapbox-style 8.0.6

Code: 
![image](https://user-images.githubusercontent.com/27947580/164391033-0bab1d52-086b-4970-bf03-0526c4b256bc.png)

Here is a link to the test repository - https://github.com/supervueman/test-ol-mapbox-style

**Comment by ahocevar** [comment]
I can reproduce this. It is related to vue's webpack config, but it should not be happening. I'm investigating what could be done on ol-mapbox-style's side to make the bundle more compatible.

**Comment by ahocevar** [comment]
Fixed in v8.0.7.

**Comment by supervueman** [comment]
Thank you, it worked!!!

**Comment by YuliyaAstak** [comment]
Thank you
