### ISSUE TITLE
Allow to override `tileJson.tiles` with urls from the original VectorTile source

### ISSUE THREAD

**Issue by boeckMt** [openlayers/ol-mapbox-style#599]
There is already the possibility to override the tile url in `applyStyle` with the [transformRequest option](https://github.com/openlayers/ol-mapbox-style/blob/v8.1.2/src/apply.js#L594) but if the TileJSON only has one endpoint configured it is not possible to create multiple urls like in the [VectorTile (urls)](https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html).

I know this shouldn't happen normally but could be helpful if there is a misconfiguration on the server side that a client might not be able to fix easily.

Maybe `options.tiles` could be passed in `applyStyle` and if that's provided use it for `sourceOptions.urls` in https://github.com/openlayers/ol-mapbox-style/blob/acdd647c791993da8d1179b554e4c5dfceed4df5/src/apply.js#L504

This could also be helpful if the client uses a `tms` service where a TileJSON may not exist.

**Comment by ahocevar** [comment]
This sounds like a quite specific use case to me. What you can do is retrieve the source that `ol-mapbox-style` created using https://github.com/openlayers/ol-mapbox-style#getsource, and use the source's `setUrls` method to configure multiple urls.
