### ISSUE TITLE
text-justify not supported

### ISSUE THREAD

**Issue by cns-solutions-admin** [openlayers/ol-mapbox-style#645]
The mapbox style property "text-justify" is not supported, although openlayers text style supports the functionality with option "justify":
* text-justify: "auto" => justify not set
* text-justify: "left" => justify: "left"
* text-justify: "center" => justify: "center"
* text-justify: "right" => justify: "right"

**Comment by ahocevar** [comment]
@cns-solutions-admin Would you be able to create a pull request that adds this missing functionality?

**Comment by cns-solutions-admin** [comment]
Yes, nearly done.
