### ISSUE TITLE
mapbox style metadata to ol properties binding

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/ol-mapbox-style#674]
Sometimes it may be useful to bind [meatdata](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#metadata) to ol object properties. For instance, to add some layer description.

**Comment by ahocevar** [comment]
There is no 1:1 mapping between Mapbox and OpenLayers `layers`, but you can do something like this:
```
const layers = getLayer(map, 'my-mapbox-layer').get('mapbox-layers');
const metadata = layers.map(layer => map.get('mapbox-style').layers.find(layer).metadata);
```

**Comment by AlenKelemen** [comment]
Yes of course, I missed map's 'mapbox-style' property added by ol-mapbox-style. Thank you.
