### ISSUE TITLE
parse bbox for geojson source

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/ol-mapbox-style#686]
Source type geojson do not parses bbox{bbox-epsg-3857} to bbox coordinates:

`"cadastreVector": {
      "type": "geojson",
      "data": "https://oss.uredjenazemlja.hr/OssWebServices/inspireService/wfs?bbox={bbox-epsg-3857}&service=WFS&version=2.0.0&request=GetFeature&PROPERTY=label&TYPENAMES=cp%3ACadastralParcel&outputFormat=json&srsName=EPSG%3A4326&token=***"
    }`
this requests query string parameters to (bbox is just copied):
`
bbox: {bbox-epsg-4326}
service: WFS
version: 2.0.0
request: GetFeature
PROPERTY: label
TYPENAMES: cp:CadastralParcel
outputFormat: json
srsName: EPSG:4326
token: ***
ref: create-feature-cadastre
`
Unlike, for raster source it parses OK.

**Comment by ahocevar** [comment]
This is a valid feature request. Do you think you'd be able to provide a pull request?

**Comment by AlenKelemen** [comment]
I will ...

**Comment by AlenKelemen** [comment]
https://github.com/openlayers/ol-mapbox-style/pull/694
