### ISSUE TITLE
Remove Google Fonts

### ISSUE THREAD

**Issue by olsp** [openlayers/ol-mapbox-style#698]
It would be great to have a version of ol-mapbox-style without the automatic loading of Google Fonts. Using Google Fonts by default does not comply with the GDPR and therefore problematic for many users.

**Comment by ahocevar** [comment]
You can easily deploy an application without automatic Google Fonts downloads when you add stylesheets with the web fonts used by your map before calling anything from ol-mapbox-style. ol-mapbox-style will only load fonts from Google Fonts that it does not find.

**Comment by ahocevar** [comment]
Every browser can render Web fonts. Only maplibre-gl-js and mapbox-gl-js can render PBF glyphs. And these PBF glyphs are usually converted from Web fonts. So my suggestion would be to ask the map service providers to publish their fonts also as CSS. Then ol-mapbox-style could take an entry like
```
"glyphs": "https://tiles.kurviger.de/v1/fonts/{fontstack}/{range}.pbf",
```
and load e.g. https.//tiles.kurviger.de/v1/fonts/{fontstack}/{range}.css

**Comment by ahocevar** [comment]
@karussell That ticket looks good. You could already automate font downloads without Google Fonts to some extent now by fetching them from https://cdn.jsdelivr.net/npm/@fontsource/. However, this would mean to download more than you need, because you cannot choose individual font weights and styles there.

ol-mapbox-style allows you to configure a function to add web fonts on the level of `src/stylefunction.js`, using the `getFonts` argument. It would be an easy improvement to make that available also as option on the `apply` and `applyStyle` functions.

**Comment by smellman** [comment]
```and load e.g. https://tiles.kurviger.de/v1/fonts/{fontstack}/{range}.css.```
This idea is ignore by Mapbox/MapLibre Style Specification.
GDPR is big problem and supports default SDF/PBF supports is better for me.
I host our font with tileserver-gl with migmix font.
It is open font but there are not host in cdn now.

**Comment by smellman** [comment]
I don't want to provide font in my site because I add new font if I find better font.
https://github.com/osmfj/tileserver-gl-site/tree/master/fonts
Predicting which fonts are available is not a concrete solution.

**Comment by ahocevar** [comment]
@smellman OpenLayers does not support PBF glyphs, so web fonts are the way to go. And it is very easy to avoid Google fonts, as you can see in this example: https://codesandbox.io/s/muddy-sea-dof9gb?file=/src/index.js. Just import the fonts that your map needs from `@fontsource`:
```js
import "@fontsource/noto-sans";
import "@fontsource/noto-serif";
import "ol/ol.css";
import "./styles.css";
import { apply } from "ol-mapbox-style";

apply(
  "map",
  "https://cdn.arcgis.com/sharing/rest/content/items/7dc6cea0b1764a1f9af2e679f642f0f5/resources/styles/root.json?f=json",
  {
    transformRequest(url, type) {
      if (type === "Source") {
        return new Request(
          url.replace("/VectorTileServer", "/VectorTileServer/")
        );
      }
    }
  }
);

**Comment by ahocevar** [comment]
I've thought about this more after good discussions at this year's FOSSGIS conference in Berlin. I suggest to add some metadata to the style json to indicate where webfonts can be downloaded:
```js
{
  "version": 8,
  "metadata": {
    "ol-webfonts": "https://mytileservergl.com/fonts/{font-family}/{fontweight}{-fontstyle}.css"
  }
  // ...
}
```
The supported templates I'm going to add will be
* {font-family}: CSS font family converted to lowercase, blanks replaced with `-`, e.g. `noto-sans`
* {Font+Family} CSS font family in original case, blanks replaced with `+`, e.g. `Noto+Sans`
* {fontweight} CSS font weight (numeric), e.g. `400`, `700`
* {fontstyle} CSS font style, e.g. `normal`, `italic`
* {-fontstyle} CSS font style other than normal, e.g. `-italic` or empty string for normal

In addition to providing fonts along with the style, this can be used to retrieve fonts from a CDN (e.g. `@fontsource`) or Google fonts. I'm also going to change the default from Google to `@fontsource`, which is equivalent to the following template:

    https://cdn.jsdelivr.net/npm/@fontsource/{font-family}/{fontweight}{-fontstyle}.css

To retain the current behavior (i.e. use Google Fonts), the template will have to be

    https://fonts.googleapis.com/css?family={Font+Family}:{fontweight}{fontstyle}
