### ISSUE TITLE
layer.setVisibility() to override mapbox style visibility ?

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/ol-mapbox-style#701]
As I understand, layer visibility is entireliy controled by mapbox style as explained in https://github.com/openlayers/ol-mapbox-style/issues/515
Maybe user would expect ol layer.setVisibility() to override mapbox style visibility ?

**Comment by ahocevar** [comment]
Probably not, because there is no 1:1 mapping between an entry in the `layers` array in the Mapbox Style document and an OpenLayers `Layer` instance.

**Comment by AlenKelemen** [comment]
Understand, and that leads to question how to control that mapping, besides creating same source with different name or changing layers order in Mapbox Style document ?
