### ISSUE TITLE
Hillshading contained in mapbox style.json not rendered

### ISSUE THREAD

**Issue by utagawal** [openlayers/ol-mapbox-style#714]
Hello,

In the style.json we are using, we have set multiple data sources, vector, raster, and raster-dem for elevation (hillshading and potentially have also hypsometric tints)

```
 "sources": {
    "contours": {
      "type": "vector",
      "url": "https://xxxxxx.com/europe-contours-copernicus.json"
    },
    "natural-earth-2": {
      "type": "raster",
      "maxzoom": 6,
      "tiles": [
        "https://xxxxx.com/naturalearth2/{z}/{x}/{y}.png"
      ]
    },
    "openmaptiles": {
      "type": "vector",
      "url": "https://xxxxx.com/data/planet.json"
    },
    "world-rgb-png": {
      "type": "raster-dem",
      "minzoom": 5,
      "maxzoom": 11,
      "encoding": "terrarium",
      "tiles": ["https://xxxxxxx.com/world/{z}/{x}/{y}.png"]
    },
    "relief-france-hd": {
      "type": "raster-dem",
      "tiles": [
        "https://xxxxxx.com /terrain/{z}/{x}/{y}.png"
      ],
      "minzoom": 6,
      "maxzoom": 15
    }
  },
```

The layer for hillshading is placed AFTER landuse and landcover layers in the style file :
```
    {
      "id": "Hillshading-france",
      "type": "hillshade",
      "source": "relief-france-hd",
      "minzoom": 7,
      "filter": ["all"],
      "layout": {"visibility": "visible"},
      "paint": {
        "hillshade-accent-color": "rgba(110, 58, 31, 1)",
        "hillshade-exaggeration": 0.5,
        "hillshade-shadow-color": "#665942",
        "hillshade-illumination-direction": 315
      }
    },
```

It is actually not rendered and we cannot find a proper way to retrofit its usage since it should be displayed within the layer order set in the style.json file.

For the other source layers we have the same problem (natural earth, contours) but the workaround solution is -almost- acceptable.

We have also not been able to find a way to reproduce the nice "accent-color" property in openlayers.

Any chance someone could implement this ?

View with Openlayer using the workarounds :
![Capture d’écran 2022-11-07 070011](https://user-images.githubusercontent.com/16464382/200236884-4a7d77d7-ac02-4371-890b-432f6fb93f01.jpg)

View with maplibre directly interpreting the style.json (we are using more detialed source for relief here) :
![Capture d’écran 2022-11-07 070034](https://user-images.githubusercontent.com/16464382/200236888-273a5f7c-e7c5-4f1f-a1b2-289abb6b22d0.jpg)

**Comment by ahocevar** [comment]
The raster-dem source type is indeed not implemented (yet).

**Comment by utagawal** [comment]
Thanks for the confirmation and the workaround : That's exactly what we did but it forces the layer to be below or above our full vector layer.
Hopefully this will be implemented soon ;-)

**Comment by utagawal** [comment]
For the accent color implementation , maybe usefull tu take inspiration from here : src/shaders/hillshade.fragment.glsl
from https://github.com/mapbox/mapbox-gl-js/pull/5286/files#diff-a826d96571ff241535a6bac52167defaabc13c91883e2529cf84608c70ca9b79
(but it's using webGL)

**Comment by ahocevar** [comment]
Thanks for digging that out, @utagawal. Do you feel comfortable to provide a pull request adding accent color? The place to add it would be the `hillshade` function in [src/shaders.js](https://github.com/openlayers/ol-mapbox-style/blob/d2225b37f2e037091400d6468e9fba2dd5b6f0eb/src/shaders.js), and you'd have to add a `data` property and pick up the accent color in the [`beforeoperations` function in `src/apply.js`](https://github.com/openlayers/ol-mapbox-style/blob/d2225b37f2e037091400d6468e9fba2dd5b6f0eb/src/apply.js#L839-L866).

**Comment by utagawal** [comment]
Thanks but unfortunatelly I'm not a dev, I can understand a bit of code but that's it...
