### ISSUE TITLE
Urls net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by joanmorilla** [openlayers/ol-mapbox-style#735]
Hi, I'm working on a web application developed in openlayers. The base maps is a raster map that uses mapbox styles. I want to change this and use vector tiles for the background map, also with mapbox styles. I'm able to render the vector tiles but with the default openlayers style. 

I tried applying the style like this
`const layer = new VectorTileLayer({declutter: true});
applyStyle(layer, 'mapbox://styles/mapbox/bright-v9', {accessToken: 'myToken'});`

also I tried using the ol/layer/MapboxVector layer like this
`layer = new MapboxVector({
      styleUrl: 'mapbox://styles/mapbox/bright-v9',
      accessToken: 'myToken',
    })`

Neither woked. Both throw the same error: net::ERR_NAME_NOT_RESOLVED

The base url should look like this:
`https://{a-d}.tiles.mapbox.com/v4/${mapboxPath}/{z}/{x}/{y}.vector.pbf?access_token=${token}`
but I noticed that the requested ulr is this:
`https://%7Ba-d%7D.tiles.mapbox.com/v4/mapbox.mapbox-streets-v7/7/64/47.vector.pbf?access_token=myToken`

I don't know why the url don't split into 4 (https://a... https://b... https://c... https://d...). When I don't apply the style, the urls split correctly and the requests are done right.

**Comment by ahocevar** [comment]
Thanks for reporting this, @joanmorilla. Looks like a regression. For now, downgrading to v9.2.0 should work around the problim. I'm looking into this right now, hoping to be able to release an updated version with a fix soon.

**Comment by joanmorilla** [comment]
Thanks for helping. Downgrading to 9.2.0 worked but a new problem appeared. I don't know if it has any relation. This is the issue:
![image](https://user-images.githubusercontent.com/69308384/204260682-52c860b7-fac6-4dfb-9039-82b077d34f59.png)

It seems to be something related with the text alignment. Any idea how to solve it?

**Comment by ahocevar** [comment]
I just published v9.2.3, which includes the fix for the original issue.
