### ISSUE TITLE
Multidirectional hillshading

### ISSUE THREAD

**Issue by utagawal** [openlayers/ol-mapbox-style#755]
Multidirectional hillshade improves terrain visualization. It combines light from different directions to represent an enhanced visualization of the terrain and to improve the appearance of regions with low relief. It improves the balance between the overexposed and shadow areas of the map. The output is suitable to use as a relief backdrop for topographical, soil, hydrological, land cover, or other thematic maps in which the data will be enhanced with topography.

source : [https://pro.arcgis.com/en/pro-app/latest/help/analysis/raster-functions/hillshade-function.htm](https://pro.arcgis.com/en/pro-app/latest/help/analysis/raster-functions/hillshade-function.htm)

```
After multiple tests, the following three lighting sources have been selected:

Azimuth | Height | Transparency
-- | -- | --
350º | 70º | 65%
15º | 60º | 50%
270º | 270º | 70%

```

source : [https://iderioja.github.io/doc_lidar_2016_processing_en/dtm_dsm/hillshade/](https://iderioja.github.io/doc_lidar_2016_processing_en/dtm_dsm/hillshade/)

An example of multidirectional hillshading code : https://github.com/qgis/QGIS/blob/6af23a67be78a04c1c6c46cf4f7fd0b38cb61e37/src/core/raster/qgshillshaderenderer.cpp

@ahocevar  @V-Roger Any possibility to extend the hillshading rendering capabilities of the library with multidirectional hillshade ?

**Comment by ahocevar** [comment]
@utagawal This is beyond the scope of ol-mapbox-style, which aims to implement a subset of mapbox-gl-js's capabilities, not a superset. Such visualisations can be done in OpenLayers, although the more complicated the calculation, the more performance will suffer.

If you want such a visualisation with ol-mapbox-style, I'd suggest you create a static tile set with the desired visualisation, and use that with a `raster` source.

**Comment by utagawal** [comment]
Allright, will post the issue at mapbox ;-)
And thanks for the implementation guidelines
