### ISSUE TITLE
Display Embedded vector layers

### ISSUE THREAD

**Issue by utagawal** [openlayers/ol-mapbox-style#762]
It seems openlayer cannot render a style embedding multiple vector layers source where eg a specific the source layer shall be displayed in between other layers (eg elevation contours).

Is this an expected behavior at this stage ? And if yes, any suggested workaround ?

**Comment by ahocevar** [comment]
Look at https://openlayers.org/en/latest/examples/mapbox-style.html. That example does this exact thing.
