### ISSUE TITLE
Hillshading - Terrain elevation encoding

### ISSUE THREAD

**Issue by utagawal** [openlayers/ol-mapbox-style#774]
In the hillshading function, only the Mapbox encoding is available to decode elevation with the formula : pixel[0] * 256 * 256 + pixel[1] * 256 + pixel[2]) * 0.1 - 10000

Terrarium / Mapzen is also possible as Mapbox elevation encoding in a Mapbox style. Decoding formula is described [here](https://github.com/tilezen/joerd/blob/master/docs/formats.md).

@V-Roger can you please help ?

**Comment by ahocevar** [comment]
This would add support for the `raster-dem` source's `encoding` option. See https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster-dem-encoding.
