### ISSUE TITLE
Hillshading - Difference with Maplibre

### ISSUE THREAD

**Issue by utagawal** [openlayers/ol-mapbox-style#777]
While the actual hill shading rendering function is available, some small differences persists compared to Maplibre.

It is probably due to the different procedure used to generate in shading the relief allowing to better render some details.

Maplibre algorithm is here : https://github.com/maplibre/maplibre-gl-js/blob/main/src/shaders/hillshade.fragment.glsl

Here is an example of (small) differences in the images below with a small advantage to Maplibre :

### Maplibre
![image](https://user-images.githubusercontent.com/16464382/210578091-cf7e922a-3270-4f63-b643-1378efa81ede.png)

### OpenLayers :
![Capture d’écran 2023-01-04 152106](https://user-images.githubusercontent.com/16464382/210578157-2fab2c5a-bdbb-43f8-8510-9fba8c9eec98.jpg)

**Comment by orangemug** [comment]
I'm also seeing this, there is a comparison in https://maparatus.github.io/ol-mapbox-style-spec/#paint_hillshade.hillshade-exaggeration if that helps, you can see the [style here](https://github.com/maparatus/ol-mapbox-style-spec/blob/20cb21226895aab6aebc8f3744bb70f473b9f988/src/test-styles.ts#L2214-L2236), and screenshot below

![Screenshot from 2023-12-14 10-19-04](https://github.com/openlayers/ol-mapbox-style/assets/235915/66f81a5b-4db9-40ba-b322-b99054bed4d4)
