### ISSUE TITLE
Some MapTiler styles do not properly show city label for certain zoom

### ISSUE THREAD

**Issue by karussell** [openlayers/ol-mapbox-style#799]
Note that this might be as well a MapTiler bug and if so, feel free to close asap :) 

I was in contact with one of their support person and the developer said to them "the absence of labels was caused probably by ol-mapbox-style plugin that is not interpreting the style correctly".

![grafik](https://user-images.githubusercontent.com/129644/218731169-8afd0043-b0b1-4eff-a40b-7fd8ef87fa21.png)
Or see directly on [their website](https://docs.maptiler.com/openlayers/vector-maps-in-openlayers/).

Note, that the labels are shown properly for [the "TileJSON" approach](https://docs.maptiler.com/openlayers/get-started/) (is this without the ol-mapbox-style plugin?) or if you use a different [v2 style](https://docs.maptiler.com/openlayers/vector-maps-in-openlayers/?mapId=basic-v2) but not for [streets-v2](https://docs.maptiler.com/openlayers/vector-maps-in-openlayers/?mapId=streets-v2).

**Comment by ahocevar** [comment]
This is indeed an ol-mapbox style - I tried to fix it during the year end holidays, but it will be quite an involved change in OpenLayers. I'm on it, but it will probably take a while.
