### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by erwanlpfr** [openlayers/ol-mapbox-style#823]
Hello,

With an empty map, just with an "apply" to my map, I have slow performance.
The FPS decrease when I am zooming or dezooming. 
The style doesn't matter since the issue is still there.

The code is simple :

```ts
    const zoomControl = new Zoom({
      duration: 500,
      className: 'ol-zoom',
      zoomInClassName: styles.zoomIn,
      zoomOutClassName: styles.zoomOut,
      delta: 1,
    });

    const map = new Map({
      view: new View(),
      target: mapDivRef.current,
      controls: [zoomControl],
    });

    olms(map, 'mapbox://styles/......', {
      accessToken: process.env.REACT_APP_KEY_MAPBOX,
    }).then((styledMap) => {
      if (onMapReady) {
        onMapReady(styledMap as Map);
      }
    })
      .catch(console.warn);
```

Do you have any type of similar issues, or does it come from mapbox ?

Thank you for your work!

**Comment by ahocevar** [comment]
This is probably because something in your React app makes the map reactive, likely in the `onMapReady()` function.

**Comment by erwanlpfr** [comment]
Hello! 

Sorry for the late reply.
I tried to disable everything on my app and keeping only the map.
My `onMapReady` function is only a bind to a redux dispatch to keep the ref in memory.

During the loading of the map I have one error and on e warning :

```
Expected value to be of type number, but found string instead.


(anonymous) | @ | instrument.js:113
-- | -- | --
  | evaluate | @ | index.js:4178
  | filterFunc | @ | index.js:7232
  | evaluateFilter | @ | index.js:8124
  | styleFunction | @ | index.js:8355
  | render | @ | VectorTileLayer.js:200
  | updateExecutorGroup_ | @ | VectorTileLayer.js:214
  | prepareTile | @ | VectorTileLayer.js:85
  | getTile | @ | VectorTileLayer.js:112
  | renderFrame | @ | TileLayer.js:237
  | render | @ | Layer.js:334
  | renderFrame | @ | Composite.js:108
  | renderFrame_ | @ | Map.js:1382
  | animationDelay_ | @ | Map.js:1252
  | sentryWrapped | @ | helpers.js:77
```
```
Refused to apply style from 'https://fonts.googleapis.com/css?family=DIN+Pro:500normal' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Maybe it comes from here.
Is there anything to disable the call to google fonts?

Thank you for your help!

**Comment by ahocevar** [comment]
Looks more to my like something (Sentry?) is hooked into everything, which explains why things are getting slow. But if you want, you can of course prevent the Google Fonts API requests by providing the required fonts in your application's css. In this case that would be the "DIN Pro" font.

**Comment by erwanlpfr** [comment]
Hello,

Thanks for your answer, and sorry for my late one!
No way to find any tip to improve the perf.

I even tried to apply style to VectorTileLayer, or to apply directly on the map and so. No success.
My question is, when I try with your example and my mapbox, everything runs smoothly. But once, I put my map it is laggy.
Can it be from the mapbox url, I use?

I can notice the lag with a tile that is not loaded on the sides or a tile that needs to be reloaded because of the zoom.
Now, I have something a bit better : 

``` typescript
const layer = new VectorTileLayer({
      declutter: true,
      updateWhileAnimating: true,
      updateWhileInteracting: true,
      preload: 32,
      renderMode: 'hybrid',
});
```

But it is not perfect and does not look like the examples.
Note that it is a map with one layer with only one MultiPolygon source.

I don't have an idea how to debug it! 

Thank your for your work!

**Comment by ahocevar** [comment]
```js
      updateWhileAnimating: true,
      updateWhileInteracting: true,
```
Remove these two, and everything will be fine. What was the reason for adding those in the first place?
