### ISSUE TITLE
updateMapboxLayer ineffective

### ISSUE THREAD

**Issue by YXYCZXY** [openlayers/ol-mapbox-style#860]
Using the updateMapboxLayer method to add a new layer did not work.
After looking at the source code, it should be necessary to replace the old layer with the new one.
The effect is realized after the replacement is complete.
![image](https://user-images.githubusercontent.com/49504688/226822118-006dd446-f8e6-4c3b-be63-7dec99bb708f.png)

**Comment by ahocevar** [comment]
Thanks for reporting this. You're right - currently the function only works under the assumption that you use `getMapboxLayer()` to get the current style, modify it, and then `updateMapboxLayer()` to update it. Would you be able to create a pull request, ideally with a test?

**Comment by YXYCZXY** [comment]
I have submitted it

**Comment by ahocevar** [comment]
Thanks, @YXYCZXY
