### ISSUE TITLE
Use the pbf vector slice published by geoserver

### ISSUE THREAD

**Issue by YXYCZXY** [openlayers/ol-mapbox-style#862]
I don't know how to load the pbf vector slice published by geoserver onto the map.
What method should I use?
![image](https://user-images.githubusercontent.com/49504688/226856555-f0ab247a-16f0-44e6-9f68-1b0afcdb852e.png)

Load error：The layer projection coordinate system is the same。
![image](https://user-images.githubusercontent.com/49504688/226857216-13b72e9d-48c5-493c-a8bf-0de6bbd76855.png)

**Comment by ahocevar** [comment]
`"scheme": "tms"` is not yet supported in ol-mapbox-style. As a workaround, you can replace `{y}` in the URL template with `{-y}`.

**Comment by YXYCZXY** [comment]
Thanks for your help
