### ISSUE TITLE
The newly added layer cannot be queried.

### ISSUE THREAD

**Issue by YXYCZXY** [openlayers/ol-mapbox-style#867]
I added a new style using the applyStyle method and the layer is displayed.
But I can't get it with the getMapboxLayer method
![image](https://user-images.githubusercontent.com/49504688/227491435-cfced26c-7ebb-4c6e-a86c-4c79ff9d20b7.png)
![image](https://user-images.githubusercontent.com/49504688/227491500-81ef5f60-3353-4532-99a8-cd5e3aae188e.png)

**Comment by ahocevar** [comment]
Maybe this should be stated in the documentation: The utility function `getMapboxLayer()`, `addMapboxLayer()`, `updateMapboxLayer()` and `removeMapboxLayer()` are only supposed to work with styles that get applied to a map or layer group, i.e. with `apply()`, not with `applyStyle()`, which applies a style to a layer.
