### ISSUE TITLE
Is there a possibility to use raster source with ol-mapbox-style 

### ISSUE THREAD

**Issue by geodatenanwendungenhamburg** [openlayers/ol-mapbox-style#876]
I have a json file with 4 different sources of which two are of type vector and two of type raster and would like to 
Why does ol-mapbox-style only support vector and geojson data but not raster. Is there another possibility or a workaround to use raster? 

```
"sources": {
    "schummerung_col-beta": {
      "type": "raster",
      "minzoom": 0,
      "maxzoom": 22,
      "tiles": ["https://sgx.geodatenzentrum.de/wms_testmap_schummerung?tiled=true&bbox={bbox-epsg-3857}&service=WMS&version=1.3.0&request=GetMap&layers=de_testmap_web_raster_colordem&styles=&crs=EPSG:3857&width=256&height=256&format=image/png&transparent=true"],
      "tileSize": 256
    },
    "schummerung_comb-beta": {
      "type": "raster",
      "minzoom": 0,
      "maxzoom": 22,
      "tiles": ["https://sgx.geodatenzentrum.de/wms_testmap_schummerung?tiled=true&bbox={bbox-epsg-3857}&service=WMS&version=1.3.0&request=GetMap&layers=de_testmap_web_raster_combshade&styles=&crs=EPSG:3857&width=256&height=256&format=image/png&transparent=true"],
      "tileSize": 256
    },
    "smarttilesHL_de": {
      "type": "vector",
      "url": "https://sgx.geodatenzentrum.de/gdz_testmap_vektor/tiles/v1/bm_web_hl_de_3857/bm_web_hl_de_3857.json"
    },
    "smarttiles_de": {
      "type": "vector",
      "url": "https://sgx.geodatenzentrum.de/gdz_testmap_vektor/tiles/v1/bm_web_de_3857/bm_web_de_3857.json"
    }
  },
      "url": "https://sgx.geodatenzentrum.de/gdz_testmap_vektor/tiles/v1/bm_web_de_3857/bm_web_de_3857.json"
    }
  },
```

**Comment by ahocevar** [comment]
What makes you think that we don't support raster sources? Use `apply()` instead of `applyStyle()` to apply the style to a whole map or a layer group. Then it will create Vector, VectorTile and ImageTile layers, representing everything you have in the Mapbox Style document.

**Comment by geodatenanwendungenhamburg** [comment]
Maybe I wasn't clear enough. I try to uses these sources in the _**_stylefunction_**_ where it says: "Creates a style function from the glStyle object for all layers that use the specified source, which needs to be a **"type": "vector" or "type": "geojson"** source and applies it to the specified OpenLayers layer."

**Comment by ahocevar** [comment]
Well, a *stylefunction* in OpenLayers is made for styling vector and vector tile layers, it is a concept not available for raster layers. Instead of `stylefunction()` or `applyStyle()` (which both only work for vector and geojson sources), you have to use `apply()`. Have you tried that?

**Comment by geodatenanwendungenhamburg** [comment]
Thank you for your answer. 
It works fine with `apply()`.
