### ISSUE TITLE
Rendering very slow when there are many text labels

### ISSUE THREAD

**Issue by rdewit** [openlayers/ol-mapbox-style#996]
Not sure if this is an `ol` or an `ol-mapbox-style` issue: with a particular ESRI VectorTile layer, the rendering slows down significantly when there are many labels to be displayed.

This is happening in ol 7.4.0 with ol-mapbox-style 10.6.0 as well as ol 8.1.0 with ol-mapbox-style 12.0.0.

## How to reproduce:

* View the Codepen app below in fullscreen mode and, if needed, slowdown the CPU speed
* Drag map and observe the app being sluggish
* Hit the zoom-out button once and drag map again. Observe the map not being sluggish.

### App:

* https://codesandbox.io/s/mapbox-style-forked-qmtrdh?file=/index.html (Codepen code)
* https://qmtrdh.csb.app/ (Codepen app)

Is there something that I can do on my side or is this a bug that needs fixing? I can provide a Chrome trace file if needed. Below is a screenshot of the trace.

![ol-mapbox-style-labels-slowdown](https://github.com/openlayers/ol-mapbox-style/assets/219691/856123b0-caf3-403b-b9b9-ea00f6ad7e27)

**Comment by ahocevar** [comment]
The Austrian cadastre also has been optimized, to include only what makes sense in tiles for the respective zoom levels. In https://kataster.bev.gv.at/#/center/16.34513,48.19256/zoom/16.1 you can see that there are probably even more labels than in your example, but the performance is much better.

**Comment by rdewit** [comment]
Thanks for the explanation where the problem lies, @ahocevar. Closing.
